import type { TenantConfig } from "../tenant.types";

export const qcTenant: TenantConfig = {
  key: "qc",
  brand: {
    name: "Quadball Canada",
    shortName: "QC",
    portalSubtitle: "Player Portal",
    adminSubtitle: "Admin Console",
    description: "Quadball Canada membership, teams, and events platform",
    marketingUrl: "https://quadballcanada.ca",
    supportEmail: "support@quadballcanada.com",
    supportName: "Quadball Canada Team",
    logoVariant: "qc",
    themeColor: "#d82929",
  },
  features: {
    qc_portal: true,
    sin_portal: false,
    membership: true,
    events: true,
    teams: true,
    members_directory: true,
    reports: true,
    payments_square: true,
    sin_admin: false,
    sin_admin_orgs: false,
    sin_admin_audit: false,
    sin_admin_notifications: false,
    sin_admin_security: false,
    sin_admin_privacy: false,
    sin_admin_forms: false,
    sin_admin_imports: false,
    sin_admin_reporting: false,
    sin_admin_analytics: false,
    sin_reporting: false,
    sin_forms: false,
    sin_imports: false,
    sin_analytics: false,
    sin_templates: true,
    sin_help_center: true,
    sin_support: true,
    sin_data_catalog: true,
    sin_data_quality: true,
    sin_walkthroughs: true,
    org_join_requests: false,
    org_invite_links: false,
    org_discoverable_default: false,
    security_core: true,
    notifications_core: true,
  },
  orgLabels: {
    governing_body: "Governing Body",
    pso: "PSO",
    league: "League",
    club: "Club",
    affiliate: "Affiliate",
  },
  orgHierarchy: {
    rootTypes: ["governing_body", "pso"],
    allowedChildren: {
      governing_body: ["pso"],
      pso: ["league", "club", "affiliate"],
      league: ["club", "affiliate"],
      club: ["affiliate"],
      affiliate: [],
    },
  },
  admin: {
    globalRoleNames: ["Solstice Admin", "Quadball Canada Admin"],
  },
};
