import type { TenantConfig } from "../tenant.types";

export const viasportTenant: TenantConfig = {
  key: "viasport",
  brand: {
    name: "viaSport BC",
    shortName: "viaSport",
    portalSubtitle: "SIN Portal",
    adminSubtitle: "Admin Console",
    description: "viaSport Strength in Numbers (SIN) data platform",
    marketingUrl: "https://viasport.ca",
    supportEmail: "support@viasport.ca",
    supportName: "viaSport BC Team",
    logoVariant: "viasport",
    themeColor: "#003B4D",
  },
  features: {
    qc_portal: false,
    sin_portal: true,
    membership: false,
    events: false,
    teams: false,
    members_directory: false,
    reports: false,
    payments_square: false,
    sin_admin: true,
    sin_admin_orgs: true,
    sin_admin_audit: true,
    sin_admin_notifications: true,
    sin_admin_security: true,
    sin_admin_privacy: true,
    sin_admin_forms: true,
    sin_admin_imports: true,
    sin_admin_reporting: true,
    sin_admin_analytics: true,
    sin_reporting: true,
    sin_forms: true,
    sin_imports: true,
    sin_analytics: true,
    sin_nl_query: true,
    sin_analytics_sql_workbench: true,
    sin_ai: true,
    sin_templates: true,
    sin_help_center: true,
    sin_support: true,
    sin_data_catalog: true,
    sin_data_quality: true,
    sin_walkthroughs: true,
    sin_global_search: true,
    org_join_requests: true,
    org_invite_links: true,
    org_discoverable_default: false,
    security_core: true,
    notifications_core: true,
  },
  orgLabels: {
    governing_body: "Governing Body",
    pso: "PSO",
    league: "League",
    club: "Club",
    affiliate: "Affiliate",
  },
  orgHierarchy: {
    rootTypes: ["governing_body"],
    allowedChildren: {
      governing_body: ["pso"],
      pso: ["league", "club", "affiliate"],
      league: ["club", "affiliate"],
      club: ["affiliate"],
      affiliate: [],
    },
  },
  admin: {
    globalRoleNames: ["Solstice Admin", "viaSport Admin"],
  },
};
