import type { TenantConfig } from "../tenant.types";

export const viasportTenant: TenantConfig = {
  key: "viasport",
  brand: {
    name: "viaSport BC",
    shortName: "viaSport",
    portalSubtitle: "SIN Portal",
    adminSubtitle: "Admin Console",
    description: "viaSport Strength in Numbers (SIN) data platform",
    marketingUrl: "https://viasport.ca",
    supportEmail: "support@viasport.ca",
    supportName: "viaSport BC Team",
    logoVariant: "viasport",
    themeColor: "#1b5fad",
  },
  features: {
    qc_portal: false,
    sin_portal: true,
    qc_membership: false,
    qc_events: false,
    qc_teams: false,
    qc_members_directory: false,
    qc_reports: false,
    qc_payments_square: false,
    sin_admin: true,
    sin_admin_orgs: true,
    sin_admin_audit: true,
    sin_admin_notifications: true,
    sin_admin_security: true,
    sin_admin_privacy: true,
    sin_admin_forms: true,
    sin_admin_imports: true,
    sin_admin_reporting: true,
    sin_admin_analytics: true,
    sin_reporting: true,
    sin_forms: true,
    sin_imports: true,
    sin_analytics: true,
    security_core: true,
    notifications_core: true,
  },
  orgLabels: {
    governing_body: "Governing Body",
    pso: "PSO",
    league: "League",
    club: "Club",
    affiliate: "Affiliate",
  },
  orgHierarchy: {
    rootTypes: ["governing_body"],
    allowedChildren: {
      governing_body: ["pso"],
      pso: ["league", "club", "affiliate"],
      league: ["club", "affiliate"],
      club: ["affiliate"],
      affiliate: [],
    },
  },
  admin: {
    globalRoleNames: ["Solstice Admin", "viaSport Admin"],
  },
};
