/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as OnboardingRouteRouteImport } from "./routes/onboarding/route";
import { Route as DashboardRouteRouteImport } from "./routes/dashboard/route";
import { Route as AuthRouteRouteImport } from "./routes/auth/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as OnboardingIndexRouteImport } from "./routes/onboarding/index";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as DashboardTeamsRouteImport } from "./routes/dashboard/teams";
import { Route as DashboardSinRouteImport } from "./routes/dashboard/sin";
import { Route as DashboardSettingsRouteImport } from "./routes/dashboard/settings";
import { Route as DashboardSelectOrgRouteImport } from "./routes/dashboard/select-org";
import { Route as DashboardReportsRouteImport } from "./routes/dashboard/reports";
import { Route as DashboardProfileRouteImport } from "./routes/dashboard/profile";
import { Route as DashboardPrivacyRouteImport } from "./routes/dashboard/privacy";
import { Route as DashboardMembershipRouteImport } from "./routes/dashboard/membership";
import { Route as DashboardMembersRouteImport } from "./routes/dashboard/members";
import { Route as DashboardForbiddenRouteImport } from "./routes/dashboard/forbidden";
import { Route as DashboardEventsRouteImport } from "./routes/dashboard/events";
import { Route as AuthSignupRouteImport } from "./routes/auth/signup";
import { Route as AuthLoginRouteImport } from "./routes/auth/login";
import { Route as ApiTestSquareRouteImport } from "./routes/api/test-square";
import { Route as ApiHealthRouteImport } from "./routes/api/health";
import { Route as ApiDebugSquareRouteImport } from "./routes/api/debug-square";
import { Route as AdminRolesRouteImport } from "./routes/admin/roles";
import { Route as DashboardAdminRouteRouteImport } from "./routes/dashboard/admin/route";
import { Route as DashboardTeamsIndexRouteImport } from "./routes/dashboard/teams/index";
import { Route as DashboardSinIndexRouteImport } from "./routes/dashboard/sin/index";
import { Route as DashboardEventsIndexRouteImport } from "./routes/dashboard/events/index";
import { Route as DashboardAdminIndexRouteImport } from "./routes/dashboard/admin/index";
import { Route as DashboardTeamsCreateRouteImport } from "./routes/dashboard/teams/create";
import { Route as DashboardTeamsBrowseRouteImport } from "./routes/dashboard/teams/browse";
import { Route as DashboardTeamsTeamIdRouteImport } from "./routes/dashboard/teams/$teamId";
import { Route as DashboardSinReportingRouteImport } from "./routes/dashboard/sin/reporting";
import { Route as DashboardSinImportsRouteImport } from "./routes/dashboard/sin/imports";
import { Route as DashboardSinFormsRouteImport } from "./routes/dashboard/sin/forms";
import { Route as DashboardSinAnalyticsRouteImport } from "./routes/dashboard/sin/analytics";
import { Route as DashboardEventsCreateRouteImport } from "./routes/dashboard/events/create";
import { Route as DashboardEventsSlugRouteImport } from "./routes/dashboard/events/$slug";
import { Route as DashboardAdminSinRouteImport } from "./routes/dashboard/admin/sin";
import { Route as DashboardAdminRolesRouteImport } from "./routes/dashboard/admin/roles";
import { Route as ApiWebhooksSquareRouteImport } from "./routes/api/webhooks/square";
import { Route as ApiTestCleanupRouteImport } from "./routes/api/test/cleanup";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as DashboardTeamsTeamIdIndexRouteImport } from "./routes/dashboard/teams/$teamId.index";
import { Route as DashboardEventsSlugIndexRouteImport } from "./routes/dashboard/events/$slug.index";
import { Route as DashboardAdminSinIndexRouteImport } from "./routes/dashboard/admin/sin/index";
import { Route as DashboardTeamsTeamIdMembersRouteImport } from "./routes/dashboard/teams/$teamId.members";
import { Route as DashboardTeamsTeamIdManageRouteImport } from "./routes/dashboard/teams/$teamId.manage";
import { Route as DashboardSinSubmissionsSubmissionIdRouteImport } from "./routes/dashboard/sin/submissions/$submissionId";
import { Route as DashboardSinFormsFormIdRouteImport } from "./routes/dashboard/sin/forms/$formId";
import { Route as DashboardEventsSlugRegisterRouteImport } from "./routes/dashboard/events/$slug.register";
import { Route as DashboardEventsEventIdManageRouteImport } from "./routes/dashboard/events/$eventId.manage";
import { Route as DashboardAdminSinSecurityRouteImport } from "./routes/dashboard/admin/sin/security";
import { Route as DashboardAdminSinReportingRouteImport } from "./routes/dashboard/admin/sin/reporting";
import { Route as DashboardAdminSinPrivacyRouteImport } from "./routes/dashboard/admin/sin/privacy";
import { Route as DashboardAdminSinOrganizationsRouteImport } from "./routes/dashboard/admin/sin/organizations";
import { Route as DashboardAdminSinNotificationsRouteImport } from "./routes/dashboard/admin/sin/notifications";
import { Route as DashboardAdminSinImportsRouteImport } from "./routes/dashboard/admin/sin/imports";
import { Route as DashboardAdminSinFormsRouteImport } from "./routes/dashboard/admin/sin/forms";
import { Route as DashboardAdminSinAuditRouteImport } from "./routes/dashboard/admin/sin/audit";
import { Route as DashboardAdminSinAnalyticsRouteImport } from "./routes/dashboard/admin/sin/analytics";
import { Route as ApiPaymentsSquareCallbackRouteImport } from "./routes/api/payments/square/callback";
import { Route as ApiAuthActionProviderRouteImport } from "./routes/api/auth/$action/$provider";

const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => OnboardingRouteRoute,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardTeamsRoute = DashboardTeamsRouteImport.update({
  id: "/teams",
  path: "/teams",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardSinRoute = DashboardSinRouteImport.update({
  id: "/sin",
  path: "/sin",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardSelectOrgRoute = DashboardSelectOrgRouteImport.update({
  id: "/select-org",
  path: "/select-org",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardPrivacyRoute = DashboardPrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardMembershipRoute = DashboardMembershipRouteImport.update({
  id: "/membership",
  path: "/membership",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: "/members",
  path: "/members",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardForbiddenRoute = DashboardForbiddenRouteImport.update({
  id: "/forbidden",
  path: "/forbidden",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: "/events",
  path: "/events",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRouteRoute,
} as any);
const ApiTestSquareRoute = ApiTestSquareRouteImport.update({
  id: "/api/test-square",
  path: "/api/test-square",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: "/api/health",
  path: "/api/health",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiDebugSquareRoute = ApiDebugSquareRouteImport.update({
  id: "/api/debug-square",
  path: "/api/debug-square",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: "/admin/roles",
  path: "/admin/roles",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardTeamsIndexRoute = DashboardTeamsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardTeamsRoute,
} as any);
const DashboardSinIndexRoute = DashboardSinIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardSinRoute,
} as any);
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardEventsRoute,
} as any);
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardAdminRouteRoute,
} as any);
const DashboardTeamsCreateRoute = DashboardTeamsCreateRouteImport.update({
  id: "/create",
  path: "/create",
  getParentRoute: () => DashboardTeamsRoute,
} as any);
const DashboardTeamsBrowseRoute = DashboardTeamsBrowseRouteImport.update({
  id: "/browse",
  path: "/browse",
  getParentRoute: () => DashboardTeamsRoute,
} as any);
const DashboardTeamsTeamIdRoute = DashboardTeamsTeamIdRouteImport.update({
  id: "/$teamId",
  path: "/$teamId",
  getParentRoute: () => DashboardTeamsRoute,
} as any);
const DashboardSinReportingRoute = DashboardSinReportingRouteImport.update({
  id: "/reporting",
  path: "/reporting",
  getParentRoute: () => DashboardSinRoute,
} as any);
const DashboardSinImportsRoute = DashboardSinImportsRouteImport.update({
  id: "/imports",
  path: "/imports",
  getParentRoute: () => DashboardSinRoute,
} as any);
const DashboardSinFormsRoute = DashboardSinFormsRouteImport.update({
  id: "/forms",
  path: "/forms",
  getParentRoute: () => DashboardSinRoute,
} as any);
const DashboardSinAnalyticsRoute = DashboardSinAnalyticsRouteImport.update({
  id: "/analytics",
  path: "/analytics",
  getParentRoute: () => DashboardSinRoute,
} as any);
const DashboardEventsCreateRoute = DashboardEventsCreateRouteImport.update({
  id: "/create",
  path: "/create",
  getParentRoute: () => DashboardEventsRoute,
} as any);
const DashboardEventsSlugRoute = DashboardEventsSlugRouteImport.update({
  id: "/$slug",
  path: "/$slug",
  getParentRoute: () => DashboardEventsRoute,
} as any);
const DashboardAdminSinRoute = DashboardAdminSinRouteImport.update({
  id: "/sin",
  path: "/sin",
  getParentRoute: () => DashboardAdminRouteRoute,
} as any);
const DashboardAdminRolesRoute = DashboardAdminRolesRouteImport.update({
  id: "/roles",
  path: "/roles",
  getParentRoute: () => DashboardAdminRouteRoute,
} as any);
const ApiWebhooksSquareRoute = ApiWebhooksSquareRouteImport.update({
  id: "/api/webhooks/square",
  path: "/api/webhooks/square",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiTestCleanupRoute = ApiTestCleanupRouteImport.update({
  id: "/api/test/cleanup",
  path: "/api/test/cleanup",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardTeamsTeamIdIndexRoute =
  DashboardTeamsTeamIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => DashboardTeamsTeamIdRoute,
  } as any);
const DashboardEventsSlugIndexRoute =
  DashboardEventsSlugIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => DashboardEventsSlugRoute,
  } as any);
const DashboardAdminSinIndexRoute = DashboardAdminSinIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardAdminSinRoute,
} as any);
const DashboardTeamsTeamIdMembersRoute =
  DashboardTeamsTeamIdMembersRouteImport.update({
    id: "/members",
    path: "/members",
    getParentRoute: () => DashboardTeamsTeamIdRoute,
  } as any);
const DashboardTeamsTeamIdManageRoute =
  DashboardTeamsTeamIdManageRouteImport.update({
    id: "/manage",
    path: "/manage",
    getParentRoute: () => DashboardTeamsTeamIdRoute,
  } as any);
const DashboardSinSubmissionsSubmissionIdRoute =
  DashboardSinSubmissionsSubmissionIdRouteImport.update({
    id: "/submissions/$submissionId",
    path: "/submissions/$submissionId",
    getParentRoute: () => DashboardSinRoute,
  } as any);
const DashboardSinFormsFormIdRoute = DashboardSinFormsFormIdRouteImport.update({
  id: "/$formId",
  path: "/$formId",
  getParentRoute: () => DashboardSinFormsRoute,
} as any);
const DashboardEventsSlugRegisterRoute =
  DashboardEventsSlugRegisterRouteImport.update({
    id: "/register",
    path: "/register",
    getParentRoute: () => DashboardEventsSlugRoute,
  } as any);
const DashboardEventsEventIdManageRoute =
  DashboardEventsEventIdManageRouteImport.update({
    id: "/$eventId/manage",
    path: "/$eventId/manage",
    getParentRoute: () => DashboardEventsRoute,
  } as any);
const DashboardAdminSinSecurityRoute =
  DashboardAdminSinSecurityRouteImport.update({
    id: "/security",
    path: "/security",
    getParentRoute: () => DashboardAdminSinRoute,
  } as any);
const DashboardAdminSinReportingRoute =
  DashboardAdminSinReportingRouteImport.update({
    id: "/reporting",
    path: "/reporting",
    getParentRoute: () => DashboardAdminSinRoute,
  } as any);
const DashboardAdminSinPrivacyRoute =
  DashboardAdminSinPrivacyRouteImport.update({
    id: "/privacy",
    path: "/privacy",
    getParentRoute: () => DashboardAdminSinRoute,
  } as any);
const DashboardAdminSinOrganizationsRoute =
  DashboardAdminSinOrganizationsRouteImport.update({
    id: "/organizations",
    path: "/organizations",
    getParentRoute: () => DashboardAdminSinRoute,
  } as any);
const DashboardAdminSinNotificationsRoute =
  DashboardAdminSinNotificationsRouteImport.update({
    id: "/notifications",
    path: "/notifications",
    getParentRoute: () => DashboardAdminSinRoute,
  } as any);
const DashboardAdminSinImportsRoute =
  DashboardAdminSinImportsRouteImport.update({
    id: "/imports",
    path: "/imports",
    getParentRoute: () => DashboardAdminSinRoute,
  } as any);
const DashboardAdminSinFormsRoute = DashboardAdminSinFormsRouteImport.update({
  id: "/forms",
  path: "/forms",
  getParentRoute: () => DashboardAdminSinRoute,
} as any);
const DashboardAdminSinAuditRoute = DashboardAdminSinAuditRouteImport.update({
  id: "/audit",
  path: "/audit",
  getParentRoute: () => DashboardAdminSinRoute,
} as any);
const DashboardAdminSinAnalyticsRoute =
  DashboardAdminSinAnalyticsRouteImport.update({
    id: "/analytics",
    path: "/analytics",
    getParentRoute: () => DashboardAdminSinRoute,
  } as any);
const ApiPaymentsSquareCallbackRoute =
  ApiPaymentsSquareCallbackRouteImport.update({
    id: "/api/payments/square/callback",
    path: "/api/payments/square/callback",
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiAuthActionProviderRoute = ApiAuthActionProviderRouteImport.update({
  id: "/api/auth/$action/$provider",
  path: "/api/auth/$action/$provider",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/onboarding": typeof OnboardingRouteRouteWithChildren;
  "/dashboard/admin": typeof DashboardAdminRouteRouteWithChildren;
  "/admin/roles": typeof AdminRolesRoute;
  "/api/debug-square": typeof ApiDebugSquareRoute;
  "/api/health": typeof ApiHealthRoute;
  "/api/test-square": typeof ApiTestSquareRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/signup": typeof AuthSignupRoute;
  "/dashboard/events": typeof DashboardEventsRouteWithChildren;
  "/dashboard/forbidden": typeof DashboardForbiddenRoute;
  "/dashboard/members": typeof DashboardMembersRoute;
  "/dashboard/membership": typeof DashboardMembershipRoute;
  "/dashboard/privacy": typeof DashboardPrivacyRoute;
  "/dashboard/profile": typeof DashboardProfileRoute;
  "/dashboard/reports": typeof DashboardReportsRoute;
  "/dashboard/select-org": typeof DashboardSelectOrgRoute;
  "/dashboard/settings": typeof DashboardSettingsRoute;
  "/dashboard/sin": typeof DashboardSinRouteWithChildren;
  "/dashboard/teams": typeof DashboardTeamsRouteWithChildren;
  "/dashboard/": typeof DashboardIndexRoute;
  "/onboarding/": typeof OnboardingIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/test/cleanup": typeof ApiTestCleanupRoute;
  "/api/webhooks/square": typeof ApiWebhooksSquareRoute;
  "/dashboard/admin/roles": typeof DashboardAdminRolesRoute;
  "/dashboard/admin/sin": typeof DashboardAdminSinRouteWithChildren;
  "/dashboard/events/$slug": typeof DashboardEventsSlugRouteWithChildren;
  "/dashboard/events/create": typeof DashboardEventsCreateRoute;
  "/dashboard/sin/analytics": typeof DashboardSinAnalyticsRoute;
  "/dashboard/sin/forms": typeof DashboardSinFormsRouteWithChildren;
  "/dashboard/sin/imports": typeof DashboardSinImportsRoute;
  "/dashboard/sin/reporting": typeof DashboardSinReportingRoute;
  "/dashboard/teams/$teamId": typeof DashboardTeamsTeamIdRouteWithChildren;
  "/dashboard/teams/browse": typeof DashboardTeamsBrowseRoute;
  "/dashboard/teams/create": typeof DashboardTeamsCreateRoute;
  "/dashboard/admin/": typeof DashboardAdminIndexRoute;
  "/dashboard/events/": typeof DashboardEventsIndexRoute;
  "/dashboard/sin/": typeof DashboardSinIndexRoute;
  "/dashboard/teams/": typeof DashboardTeamsIndexRoute;
  "/api/auth/$action/$provider": typeof ApiAuthActionProviderRoute;
  "/api/payments/square/callback": typeof ApiPaymentsSquareCallbackRoute;
  "/dashboard/admin/sin/analytics": typeof DashboardAdminSinAnalyticsRoute;
  "/dashboard/admin/sin/audit": typeof DashboardAdminSinAuditRoute;
  "/dashboard/admin/sin/forms": typeof DashboardAdminSinFormsRoute;
  "/dashboard/admin/sin/imports": typeof DashboardAdminSinImportsRoute;
  "/dashboard/admin/sin/notifications": typeof DashboardAdminSinNotificationsRoute;
  "/dashboard/admin/sin/organizations": typeof DashboardAdminSinOrganizationsRoute;
  "/dashboard/admin/sin/privacy": typeof DashboardAdminSinPrivacyRoute;
  "/dashboard/admin/sin/reporting": typeof DashboardAdminSinReportingRoute;
  "/dashboard/admin/sin/security": typeof DashboardAdminSinSecurityRoute;
  "/dashboard/events/$eventId/manage": typeof DashboardEventsEventIdManageRoute;
  "/dashboard/events/$slug/register": typeof DashboardEventsSlugRegisterRoute;
  "/dashboard/sin/forms/$formId": typeof DashboardSinFormsFormIdRoute;
  "/dashboard/sin/submissions/$submissionId": typeof DashboardSinSubmissionsSubmissionIdRoute;
  "/dashboard/teams/$teamId/manage": typeof DashboardTeamsTeamIdManageRoute;
  "/dashboard/teams/$teamId/members": typeof DashboardTeamsTeamIdMembersRoute;
  "/dashboard/admin/sin/": typeof DashboardAdminSinIndexRoute;
  "/dashboard/events/$slug/": typeof DashboardEventsSlugIndexRoute;
  "/dashboard/teams/$teamId/": typeof DashboardTeamsTeamIdIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/admin/roles": typeof AdminRolesRoute;
  "/api/debug-square": typeof ApiDebugSquareRoute;
  "/api/health": typeof ApiHealthRoute;
  "/api/test-square": typeof ApiTestSquareRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/signup": typeof AuthSignupRoute;
  "/dashboard/forbidden": typeof DashboardForbiddenRoute;
  "/dashboard/members": typeof DashboardMembersRoute;
  "/dashboard/membership": typeof DashboardMembershipRoute;
  "/dashboard/privacy": typeof DashboardPrivacyRoute;
  "/dashboard/profile": typeof DashboardProfileRoute;
  "/dashboard/reports": typeof DashboardReportsRoute;
  "/dashboard/select-org": typeof DashboardSelectOrgRoute;
  "/dashboard/settings": typeof DashboardSettingsRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/onboarding": typeof OnboardingIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/test/cleanup": typeof ApiTestCleanupRoute;
  "/api/webhooks/square": typeof ApiWebhooksSquareRoute;
  "/dashboard/admin/roles": typeof DashboardAdminRolesRoute;
  "/dashboard/events/create": typeof DashboardEventsCreateRoute;
  "/dashboard/sin/analytics": typeof DashboardSinAnalyticsRoute;
  "/dashboard/sin/forms": typeof DashboardSinFormsRouteWithChildren;
  "/dashboard/sin/imports": typeof DashboardSinImportsRoute;
  "/dashboard/sin/reporting": typeof DashboardSinReportingRoute;
  "/dashboard/teams/browse": typeof DashboardTeamsBrowseRoute;
  "/dashboard/teams/create": typeof DashboardTeamsCreateRoute;
  "/dashboard/admin": typeof DashboardAdminIndexRoute;
  "/dashboard/events": typeof DashboardEventsIndexRoute;
  "/dashboard/sin": typeof DashboardSinIndexRoute;
  "/dashboard/teams": typeof DashboardTeamsIndexRoute;
  "/api/auth/$action/$provider": typeof ApiAuthActionProviderRoute;
  "/api/payments/square/callback": typeof ApiPaymentsSquareCallbackRoute;
  "/dashboard/admin/sin/analytics": typeof DashboardAdminSinAnalyticsRoute;
  "/dashboard/admin/sin/audit": typeof DashboardAdminSinAuditRoute;
  "/dashboard/admin/sin/forms": typeof DashboardAdminSinFormsRoute;
  "/dashboard/admin/sin/imports": typeof DashboardAdminSinImportsRoute;
  "/dashboard/admin/sin/notifications": typeof DashboardAdminSinNotificationsRoute;
  "/dashboard/admin/sin/organizations": typeof DashboardAdminSinOrganizationsRoute;
  "/dashboard/admin/sin/privacy": typeof DashboardAdminSinPrivacyRoute;
  "/dashboard/admin/sin/reporting": typeof DashboardAdminSinReportingRoute;
  "/dashboard/admin/sin/security": typeof DashboardAdminSinSecurityRoute;
  "/dashboard/events/$eventId/manage": typeof DashboardEventsEventIdManageRoute;
  "/dashboard/events/$slug/register": typeof DashboardEventsSlugRegisterRoute;
  "/dashboard/sin/forms/$formId": typeof DashboardSinFormsFormIdRoute;
  "/dashboard/sin/submissions/$submissionId": typeof DashboardSinSubmissionsSubmissionIdRoute;
  "/dashboard/teams/$teamId/manage": typeof DashboardTeamsTeamIdManageRoute;
  "/dashboard/teams/$teamId/members": typeof DashboardTeamsTeamIdMembersRoute;
  "/dashboard/admin/sin": typeof DashboardAdminSinIndexRoute;
  "/dashboard/events/$slug": typeof DashboardEventsSlugIndexRoute;
  "/dashboard/teams/$teamId": typeof DashboardTeamsTeamIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/onboarding": typeof OnboardingRouteRouteWithChildren;
  "/dashboard/admin": typeof DashboardAdminRouteRouteWithChildren;
  "/admin/roles": typeof AdminRolesRoute;
  "/api/debug-square": typeof ApiDebugSquareRoute;
  "/api/health": typeof ApiHealthRoute;
  "/api/test-square": typeof ApiTestSquareRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/signup": typeof AuthSignupRoute;
  "/dashboard/events": typeof DashboardEventsRouteWithChildren;
  "/dashboard/forbidden": typeof DashboardForbiddenRoute;
  "/dashboard/members": typeof DashboardMembersRoute;
  "/dashboard/membership": typeof DashboardMembershipRoute;
  "/dashboard/privacy": typeof DashboardPrivacyRoute;
  "/dashboard/profile": typeof DashboardProfileRoute;
  "/dashboard/reports": typeof DashboardReportsRoute;
  "/dashboard/select-org": typeof DashboardSelectOrgRoute;
  "/dashboard/settings": typeof DashboardSettingsRoute;
  "/dashboard/sin": typeof DashboardSinRouteWithChildren;
  "/dashboard/teams": typeof DashboardTeamsRouteWithChildren;
  "/dashboard/": typeof DashboardIndexRoute;
  "/onboarding/": typeof OnboardingIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/test/cleanup": typeof ApiTestCleanupRoute;
  "/api/webhooks/square": typeof ApiWebhooksSquareRoute;
  "/dashboard/admin/roles": typeof DashboardAdminRolesRoute;
  "/dashboard/admin/sin": typeof DashboardAdminSinRouteWithChildren;
  "/dashboard/events/$slug": typeof DashboardEventsSlugRouteWithChildren;
  "/dashboard/events/create": typeof DashboardEventsCreateRoute;
  "/dashboard/sin/analytics": typeof DashboardSinAnalyticsRoute;
  "/dashboard/sin/forms": typeof DashboardSinFormsRouteWithChildren;
  "/dashboard/sin/imports": typeof DashboardSinImportsRoute;
  "/dashboard/sin/reporting": typeof DashboardSinReportingRoute;
  "/dashboard/teams/$teamId": typeof DashboardTeamsTeamIdRouteWithChildren;
  "/dashboard/teams/browse": typeof DashboardTeamsBrowseRoute;
  "/dashboard/teams/create": typeof DashboardTeamsCreateRoute;
  "/dashboard/admin/": typeof DashboardAdminIndexRoute;
  "/dashboard/events/": typeof DashboardEventsIndexRoute;
  "/dashboard/sin/": typeof DashboardSinIndexRoute;
  "/dashboard/teams/": typeof DashboardTeamsIndexRoute;
  "/api/auth/$action/$provider": typeof ApiAuthActionProviderRoute;
  "/api/payments/square/callback": typeof ApiPaymentsSquareCallbackRoute;
  "/dashboard/admin/sin/analytics": typeof DashboardAdminSinAnalyticsRoute;
  "/dashboard/admin/sin/audit": typeof DashboardAdminSinAuditRoute;
  "/dashboard/admin/sin/forms": typeof DashboardAdminSinFormsRoute;
  "/dashboard/admin/sin/imports": typeof DashboardAdminSinImportsRoute;
  "/dashboard/admin/sin/notifications": typeof DashboardAdminSinNotificationsRoute;
  "/dashboard/admin/sin/organizations": typeof DashboardAdminSinOrganizationsRoute;
  "/dashboard/admin/sin/privacy": typeof DashboardAdminSinPrivacyRoute;
  "/dashboard/admin/sin/reporting": typeof DashboardAdminSinReportingRoute;
  "/dashboard/admin/sin/security": typeof DashboardAdminSinSecurityRoute;
  "/dashboard/events/$eventId/manage": typeof DashboardEventsEventIdManageRoute;
  "/dashboard/events/$slug/register": typeof DashboardEventsSlugRegisterRoute;
  "/dashboard/sin/forms/$formId": typeof DashboardSinFormsFormIdRoute;
  "/dashboard/sin/submissions/$submissionId": typeof DashboardSinSubmissionsSubmissionIdRoute;
  "/dashboard/teams/$teamId/manage": typeof DashboardTeamsTeamIdManageRoute;
  "/dashboard/teams/$teamId/members": typeof DashboardTeamsTeamIdMembersRoute;
  "/dashboard/admin/sin/": typeof DashboardAdminSinIndexRoute;
  "/dashboard/events/$slug/": typeof DashboardEventsSlugIndexRoute;
  "/dashboard/teams/$teamId/": typeof DashboardTeamsTeamIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/auth"
    | "/dashboard"
    | "/onboarding"
    | "/dashboard/admin"
    | "/admin/roles"
    | "/api/debug-square"
    | "/api/health"
    | "/api/test-square"
    | "/auth/login"
    | "/auth/signup"
    | "/dashboard/events"
    | "/dashboard/forbidden"
    | "/dashboard/members"
    | "/dashboard/membership"
    | "/dashboard/privacy"
    | "/dashboard/profile"
    | "/dashboard/reports"
    | "/dashboard/select-org"
    | "/dashboard/settings"
    | "/dashboard/sin"
    | "/dashboard/teams"
    | "/dashboard/"
    | "/onboarding/"
    | "/api/auth/$"
    | "/api/test/cleanup"
    | "/api/webhooks/square"
    | "/dashboard/admin/roles"
    | "/dashboard/admin/sin"
    | "/dashboard/events/$slug"
    | "/dashboard/events/create"
    | "/dashboard/sin/analytics"
    | "/dashboard/sin/forms"
    | "/dashboard/sin/imports"
    | "/dashboard/sin/reporting"
    | "/dashboard/teams/$teamId"
    | "/dashboard/teams/browse"
    | "/dashboard/teams/create"
    | "/dashboard/admin/"
    | "/dashboard/events/"
    | "/dashboard/sin/"
    | "/dashboard/teams/"
    | "/api/auth/$action/$provider"
    | "/api/payments/square/callback"
    | "/dashboard/admin/sin/analytics"
    | "/dashboard/admin/sin/audit"
    | "/dashboard/admin/sin/forms"
    | "/dashboard/admin/sin/imports"
    | "/dashboard/admin/sin/notifications"
    | "/dashboard/admin/sin/organizations"
    | "/dashboard/admin/sin/privacy"
    | "/dashboard/admin/sin/reporting"
    | "/dashboard/admin/sin/security"
    | "/dashboard/events/$eventId/manage"
    | "/dashboard/events/$slug/register"
    | "/dashboard/sin/forms/$formId"
    | "/dashboard/sin/submissions/$submissionId"
    | "/dashboard/teams/$teamId/manage"
    | "/dashboard/teams/$teamId/members"
    | "/dashboard/admin/sin/"
    | "/dashboard/events/$slug/"
    | "/dashboard/teams/$teamId/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/auth"
    | "/admin/roles"
    | "/api/debug-square"
    | "/api/health"
    | "/api/test-square"
    | "/auth/login"
    | "/auth/signup"
    | "/dashboard/forbidden"
    | "/dashboard/members"
    | "/dashboard/membership"
    | "/dashboard/privacy"
    | "/dashboard/profile"
    | "/dashboard/reports"
    | "/dashboard/select-org"
    | "/dashboard/settings"
    | "/dashboard"
    | "/onboarding"
    | "/api/auth/$"
    | "/api/test/cleanup"
    | "/api/webhooks/square"
    | "/dashboard/admin/roles"
    | "/dashboard/events/create"
    | "/dashboard/sin/analytics"
    | "/dashboard/sin/forms"
    | "/dashboard/sin/imports"
    | "/dashboard/sin/reporting"
    | "/dashboard/teams/browse"
    | "/dashboard/teams/create"
    | "/dashboard/admin"
    | "/dashboard/events"
    | "/dashboard/sin"
    | "/dashboard/teams"
    | "/api/auth/$action/$provider"
    | "/api/payments/square/callback"
    | "/dashboard/admin/sin/analytics"
    | "/dashboard/admin/sin/audit"
    | "/dashboard/admin/sin/forms"
    | "/dashboard/admin/sin/imports"
    | "/dashboard/admin/sin/notifications"
    | "/dashboard/admin/sin/organizations"
    | "/dashboard/admin/sin/privacy"
    | "/dashboard/admin/sin/reporting"
    | "/dashboard/admin/sin/security"
    | "/dashboard/events/$eventId/manage"
    | "/dashboard/events/$slug/register"
    | "/dashboard/sin/forms/$formId"
    | "/dashboard/sin/submissions/$submissionId"
    | "/dashboard/teams/$teamId/manage"
    | "/dashboard/teams/$teamId/members"
    | "/dashboard/admin/sin"
    | "/dashboard/events/$slug"
    | "/dashboard/teams/$teamId";
  id:
    | "__root__"
    | "/"
    | "/auth"
    | "/dashboard"
    | "/onboarding"
    | "/dashboard/admin"
    | "/admin/roles"
    | "/api/debug-square"
    | "/api/health"
    | "/api/test-square"
    | "/auth/login"
    | "/auth/signup"
    | "/dashboard/events"
    | "/dashboard/forbidden"
    | "/dashboard/members"
    | "/dashboard/membership"
    | "/dashboard/privacy"
    | "/dashboard/profile"
    | "/dashboard/reports"
    | "/dashboard/select-org"
    | "/dashboard/settings"
    | "/dashboard/sin"
    | "/dashboard/teams"
    | "/dashboard/"
    | "/onboarding/"
    | "/api/auth/$"
    | "/api/test/cleanup"
    | "/api/webhooks/square"
    | "/dashboard/admin/roles"
    | "/dashboard/admin/sin"
    | "/dashboard/events/$slug"
    | "/dashboard/events/create"
    | "/dashboard/sin/analytics"
    | "/dashboard/sin/forms"
    | "/dashboard/sin/imports"
    | "/dashboard/sin/reporting"
    | "/dashboard/teams/$teamId"
    | "/dashboard/teams/browse"
    | "/dashboard/teams/create"
    | "/dashboard/admin/"
    | "/dashboard/events/"
    | "/dashboard/sin/"
    | "/dashboard/teams/"
    | "/api/auth/$action/$provider"
    | "/api/payments/square/callback"
    | "/dashboard/admin/sin/analytics"
    | "/dashboard/admin/sin/audit"
    | "/dashboard/admin/sin/forms"
    | "/dashboard/admin/sin/imports"
    | "/dashboard/admin/sin/notifications"
    | "/dashboard/admin/sin/organizations"
    | "/dashboard/admin/sin/privacy"
    | "/dashboard/admin/sin/reporting"
    | "/dashboard/admin/sin/security"
    | "/dashboard/events/$eventId/manage"
    | "/dashboard/events/$slug/register"
    | "/dashboard/sin/forms/$formId"
    | "/dashboard/sin/submissions/$submissionId"
    | "/dashboard/teams/$teamId/manage"
    | "/dashboard/teams/$teamId/members"
    | "/dashboard/admin/sin/"
    | "/dashboard/events/$slug/"
    | "/dashboard/teams/$teamId/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRouteRoute: typeof AuthRouteRouteWithChildren;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren;
  AdminRolesRoute: typeof AdminRolesRoute;
  ApiDebugSquareRoute: typeof ApiDebugSquareRoute;
  ApiHealthRoute: typeof ApiHealthRoute;
  ApiTestSquareRoute: typeof ApiTestSquareRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiTestCleanupRoute: typeof ApiTestCleanupRoute;
  ApiWebhooksSquareRoute: typeof ApiWebhooksSquareRoute;
  ApiAuthActionProviderRoute: typeof ApiAuthActionProviderRoute;
  ApiPaymentsSquareCallbackRoute: typeof ApiPaymentsSquareCallbackRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/onboarding": {
      id: "/onboarding";
      path: "/onboarding";
      fullPath: "/onboarding";
      preLoaderRoute: typeof OnboardingRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth": {
      id: "/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/onboarding/": {
      id: "/onboarding/";
      path: "/";
      fullPath: "/onboarding/";
      preLoaderRoute: typeof OnboardingIndexRouteImport;
      parentRoute: typeof OnboardingRouteRoute;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/teams": {
      id: "/dashboard/teams";
      path: "/teams";
      fullPath: "/dashboard/teams";
      preLoaderRoute: typeof DashboardTeamsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/sin": {
      id: "/dashboard/sin";
      path: "/sin";
      fullPath: "/dashboard/sin";
      preLoaderRoute: typeof DashboardSinRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings": {
      id: "/dashboard/settings";
      path: "/settings";
      fullPath: "/dashboard/settings";
      preLoaderRoute: typeof DashboardSettingsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/select-org": {
      id: "/dashboard/select-org";
      path: "/select-org";
      fullPath: "/dashboard/select-org";
      preLoaderRoute: typeof DashboardSelectOrgRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/reports": {
      id: "/dashboard/reports";
      path: "/reports";
      fullPath: "/dashboard/reports";
      preLoaderRoute: typeof DashboardReportsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/profile": {
      id: "/dashboard/profile";
      path: "/profile";
      fullPath: "/dashboard/profile";
      preLoaderRoute: typeof DashboardProfileRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/privacy": {
      id: "/dashboard/privacy";
      path: "/privacy";
      fullPath: "/dashboard/privacy";
      preLoaderRoute: typeof DashboardPrivacyRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/membership": {
      id: "/dashboard/membership";
      path: "/membership";
      fullPath: "/dashboard/membership";
      preLoaderRoute: typeof DashboardMembershipRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/members": {
      id: "/dashboard/members";
      path: "/members";
      fullPath: "/dashboard/members";
      preLoaderRoute: typeof DashboardMembersRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/forbidden": {
      id: "/dashboard/forbidden";
      path: "/forbidden";
      fullPath: "/dashboard/forbidden";
      preLoaderRoute: typeof DashboardForbiddenRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/events": {
      id: "/dashboard/events";
      path: "/events";
      fullPath: "/dashboard/events";
      preLoaderRoute: typeof DashboardEventsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/auth/signup": {
      id: "/auth/signup";
      path: "/signup";
      fullPath: "/auth/signup";
      preLoaderRoute: typeof AuthSignupRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/api/test-square": {
      id: "/api/test-square";
      path: "/api/test-square";
      fullPath: "/api/test-square";
      preLoaderRoute: typeof ApiTestSquareRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/health": {
      id: "/api/health";
      path: "/api/health";
      fullPath: "/api/health";
      preLoaderRoute: typeof ApiHealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/debug-square": {
      id: "/api/debug-square";
      path: "/api/debug-square";
      fullPath: "/api/debug-square";
      preLoaderRoute: typeof ApiDebugSquareRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/roles": {
      id: "/admin/roles";
      path: "/admin/roles";
      fullPath: "/admin/roles";
      preLoaderRoute: typeof AdminRolesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/admin": {
      id: "/dashboard/admin";
      path: "/admin";
      fullPath: "/dashboard/admin";
      preLoaderRoute: typeof DashboardAdminRouteRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/teams/": {
      id: "/dashboard/teams/";
      path: "/";
      fullPath: "/dashboard/teams/";
      preLoaderRoute: typeof DashboardTeamsIndexRouteImport;
      parentRoute: typeof DashboardTeamsRoute;
    };
    "/dashboard/sin/": {
      id: "/dashboard/sin/";
      path: "/";
      fullPath: "/dashboard/sin/";
      preLoaderRoute: typeof DashboardSinIndexRouteImport;
      parentRoute: typeof DashboardSinRoute;
    };
    "/dashboard/events/": {
      id: "/dashboard/events/";
      path: "/";
      fullPath: "/dashboard/events/";
      preLoaderRoute: typeof DashboardEventsIndexRouteImport;
      parentRoute: typeof DashboardEventsRoute;
    };
    "/dashboard/admin/": {
      id: "/dashboard/admin/";
      path: "/";
      fullPath: "/dashboard/admin/";
      preLoaderRoute: typeof DashboardAdminIndexRouteImport;
      parentRoute: typeof DashboardAdminRouteRoute;
    };
    "/dashboard/teams/create": {
      id: "/dashboard/teams/create";
      path: "/create";
      fullPath: "/dashboard/teams/create";
      preLoaderRoute: typeof DashboardTeamsCreateRouteImport;
      parentRoute: typeof DashboardTeamsRoute;
    };
    "/dashboard/teams/browse": {
      id: "/dashboard/teams/browse";
      path: "/browse";
      fullPath: "/dashboard/teams/browse";
      preLoaderRoute: typeof DashboardTeamsBrowseRouteImport;
      parentRoute: typeof DashboardTeamsRoute;
    };
    "/dashboard/teams/$teamId": {
      id: "/dashboard/teams/$teamId";
      path: "/$teamId";
      fullPath: "/dashboard/teams/$teamId";
      preLoaderRoute: typeof DashboardTeamsTeamIdRouteImport;
      parentRoute: typeof DashboardTeamsRoute;
    };
    "/dashboard/sin/reporting": {
      id: "/dashboard/sin/reporting";
      path: "/reporting";
      fullPath: "/dashboard/sin/reporting";
      preLoaderRoute: typeof DashboardSinReportingRouteImport;
      parentRoute: typeof DashboardSinRoute;
    };
    "/dashboard/sin/imports": {
      id: "/dashboard/sin/imports";
      path: "/imports";
      fullPath: "/dashboard/sin/imports";
      preLoaderRoute: typeof DashboardSinImportsRouteImport;
      parentRoute: typeof DashboardSinRoute;
    };
    "/dashboard/sin/forms": {
      id: "/dashboard/sin/forms";
      path: "/forms";
      fullPath: "/dashboard/sin/forms";
      preLoaderRoute: typeof DashboardSinFormsRouteImport;
      parentRoute: typeof DashboardSinRoute;
    };
    "/dashboard/sin/analytics": {
      id: "/dashboard/sin/analytics";
      path: "/analytics";
      fullPath: "/dashboard/sin/analytics";
      preLoaderRoute: typeof DashboardSinAnalyticsRouteImport;
      parentRoute: typeof DashboardSinRoute;
    };
    "/dashboard/events/create": {
      id: "/dashboard/events/create";
      path: "/create";
      fullPath: "/dashboard/events/create";
      preLoaderRoute: typeof DashboardEventsCreateRouteImport;
      parentRoute: typeof DashboardEventsRoute;
    };
    "/dashboard/events/$slug": {
      id: "/dashboard/events/$slug";
      path: "/$slug";
      fullPath: "/dashboard/events/$slug";
      preLoaderRoute: typeof DashboardEventsSlugRouteImport;
      parentRoute: typeof DashboardEventsRoute;
    };
    "/dashboard/admin/sin": {
      id: "/dashboard/admin/sin";
      path: "/sin";
      fullPath: "/dashboard/admin/sin";
      preLoaderRoute: typeof DashboardAdminSinRouteImport;
      parentRoute: typeof DashboardAdminRouteRoute;
    };
    "/dashboard/admin/roles": {
      id: "/dashboard/admin/roles";
      path: "/roles";
      fullPath: "/dashboard/admin/roles";
      preLoaderRoute: typeof DashboardAdminRolesRouteImport;
      parentRoute: typeof DashboardAdminRouteRoute;
    };
    "/api/webhooks/square": {
      id: "/api/webhooks/square";
      path: "/api/webhooks/square";
      fullPath: "/api/webhooks/square";
      preLoaderRoute: typeof ApiWebhooksSquareRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/test/cleanup": {
      id: "/api/test/cleanup";
      path: "/api/test/cleanup";
      fullPath: "/api/test/cleanup";
      preLoaderRoute: typeof ApiTestCleanupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/teams/$teamId/": {
      id: "/dashboard/teams/$teamId/";
      path: "/";
      fullPath: "/dashboard/teams/$teamId/";
      preLoaderRoute: typeof DashboardTeamsTeamIdIndexRouteImport;
      parentRoute: typeof DashboardTeamsTeamIdRoute;
    };
    "/dashboard/events/$slug/": {
      id: "/dashboard/events/$slug/";
      path: "/";
      fullPath: "/dashboard/events/$slug/";
      preLoaderRoute: typeof DashboardEventsSlugIndexRouteImport;
      parentRoute: typeof DashboardEventsSlugRoute;
    };
    "/dashboard/admin/sin/": {
      id: "/dashboard/admin/sin/";
      path: "/";
      fullPath: "/dashboard/admin/sin/";
      preLoaderRoute: typeof DashboardAdminSinIndexRouteImport;
      parentRoute: typeof DashboardAdminSinRoute;
    };
    "/dashboard/teams/$teamId/members": {
      id: "/dashboard/teams/$teamId/members";
      path: "/members";
      fullPath: "/dashboard/teams/$teamId/members";
      preLoaderRoute: typeof DashboardTeamsTeamIdMembersRouteImport;
      parentRoute: typeof DashboardTeamsTeamIdRoute;
    };
    "/dashboard/teams/$teamId/manage": {
      id: "/dashboard/teams/$teamId/manage";
      path: "/manage";
      fullPath: "/dashboard/teams/$teamId/manage";
      preLoaderRoute: typeof DashboardTeamsTeamIdManageRouteImport;
      parentRoute: typeof DashboardTeamsTeamIdRoute;
    };
    "/dashboard/sin/submissions/$submissionId": {
      id: "/dashboard/sin/submissions/$submissionId";
      path: "/submissions/$submissionId";
      fullPath: "/dashboard/sin/submissions/$submissionId";
      preLoaderRoute: typeof DashboardSinSubmissionsSubmissionIdRouteImport;
      parentRoute: typeof DashboardSinRoute;
    };
    "/dashboard/sin/forms/$formId": {
      id: "/dashboard/sin/forms/$formId";
      path: "/$formId";
      fullPath: "/dashboard/sin/forms/$formId";
      preLoaderRoute: typeof DashboardSinFormsFormIdRouteImport;
      parentRoute: typeof DashboardSinFormsRoute;
    };
    "/dashboard/events/$slug/register": {
      id: "/dashboard/events/$slug/register";
      path: "/register";
      fullPath: "/dashboard/events/$slug/register";
      preLoaderRoute: typeof DashboardEventsSlugRegisterRouteImport;
      parentRoute: typeof DashboardEventsSlugRoute;
    };
    "/dashboard/events/$eventId/manage": {
      id: "/dashboard/events/$eventId/manage";
      path: "/$eventId/manage";
      fullPath: "/dashboard/events/$eventId/manage";
      preLoaderRoute: typeof DashboardEventsEventIdManageRouteImport;
      parentRoute: typeof DashboardEventsRoute;
    };
    "/dashboard/admin/sin/security": {
      id: "/dashboard/admin/sin/security";
      path: "/security";
      fullPath: "/dashboard/admin/sin/security";
      preLoaderRoute: typeof DashboardAdminSinSecurityRouteImport;
      parentRoute: typeof DashboardAdminSinRoute;
    };
    "/dashboard/admin/sin/reporting": {
      id: "/dashboard/admin/sin/reporting";
      path: "/reporting";
      fullPath: "/dashboard/admin/sin/reporting";
      preLoaderRoute: typeof DashboardAdminSinReportingRouteImport;
      parentRoute: typeof DashboardAdminSinRoute;
    };
    "/dashboard/admin/sin/privacy": {
      id: "/dashboard/admin/sin/privacy";
      path: "/privacy";
      fullPath: "/dashboard/admin/sin/privacy";
      preLoaderRoute: typeof DashboardAdminSinPrivacyRouteImport;
      parentRoute: typeof DashboardAdminSinRoute;
    };
    "/dashboard/admin/sin/organizations": {
      id: "/dashboard/admin/sin/organizations";
      path: "/organizations";
      fullPath: "/dashboard/admin/sin/organizations";
      preLoaderRoute: typeof DashboardAdminSinOrganizationsRouteImport;
      parentRoute: typeof DashboardAdminSinRoute;
    };
    "/dashboard/admin/sin/notifications": {
      id: "/dashboard/admin/sin/notifications";
      path: "/notifications";
      fullPath: "/dashboard/admin/sin/notifications";
      preLoaderRoute: typeof DashboardAdminSinNotificationsRouteImport;
      parentRoute: typeof DashboardAdminSinRoute;
    };
    "/dashboard/admin/sin/imports": {
      id: "/dashboard/admin/sin/imports";
      path: "/imports";
      fullPath: "/dashboard/admin/sin/imports";
      preLoaderRoute: typeof DashboardAdminSinImportsRouteImport;
      parentRoute: typeof DashboardAdminSinRoute;
    };
    "/dashboard/admin/sin/forms": {
      id: "/dashboard/admin/sin/forms";
      path: "/forms";
      fullPath: "/dashboard/admin/sin/forms";
      preLoaderRoute: typeof DashboardAdminSinFormsRouteImport;
      parentRoute: typeof DashboardAdminSinRoute;
    };
    "/dashboard/admin/sin/audit": {
      id: "/dashboard/admin/sin/audit";
      path: "/audit";
      fullPath: "/dashboard/admin/sin/audit";
      preLoaderRoute: typeof DashboardAdminSinAuditRouteImport;
      parentRoute: typeof DashboardAdminSinRoute;
    };
    "/dashboard/admin/sin/analytics": {
      id: "/dashboard/admin/sin/analytics";
      path: "/analytics";
      fullPath: "/dashboard/admin/sin/analytics";
      preLoaderRoute: typeof DashboardAdminSinAnalyticsRouteImport;
      parentRoute: typeof DashboardAdminSinRoute;
    };
    "/api/payments/square/callback": {
      id: "/api/payments/square/callback";
      path: "/api/payments/square/callback";
      fullPath: "/api/payments/square/callback";
      preLoaderRoute: typeof ApiPaymentsSquareCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$action/$provider": {
      id: "/api/auth/$action/$provider";
      path: "/api/auth/$action/$provider";
      fullPath: "/api/auth/$action/$provider";
      preLoaderRoute: typeof ApiAuthActionProviderRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthSignupRoute: typeof AuthSignupRoute;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
);

interface DashboardAdminSinRouteChildren {
  DashboardAdminSinAnalyticsRoute: typeof DashboardAdminSinAnalyticsRoute;
  DashboardAdminSinAuditRoute: typeof DashboardAdminSinAuditRoute;
  DashboardAdminSinFormsRoute: typeof DashboardAdminSinFormsRoute;
  DashboardAdminSinImportsRoute: typeof DashboardAdminSinImportsRoute;
  DashboardAdminSinNotificationsRoute: typeof DashboardAdminSinNotificationsRoute;
  DashboardAdminSinOrganizationsRoute: typeof DashboardAdminSinOrganizationsRoute;
  DashboardAdminSinPrivacyRoute: typeof DashboardAdminSinPrivacyRoute;
  DashboardAdminSinReportingRoute: typeof DashboardAdminSinReportingRoute;
  DashboardAdminSinSecurityRoute: typeof DashboardAdminSinSecurityRoute;
  DashboardAdminSinIndexRoute: typeof DashboardAdminSinIndexRoute;
}

const DashboardAdminSinRouteChildren: DashboardAdminSinRouteChildren = {
  DashboardAdminSinAnalyticsRoute: DashboardAdminSinAnalyticsRoute,
  DashboardAdminSinAuditRoute: DashboardAdminSinAuditRoute,
  DashboardAdminSinFormsRoute: DashboardAdminSinFormsRoute,
  DashboardAdminSinImportsRoute: DashboardAdminSinImportsRoute,
  DashboardAdminSinNotificationsRoute: DashboardAdminSinNotificationsRoute,
  DashboardAdminSinOrganizationsRoute: DashboardAdminSinOrganizationsRoute,
  DashboardAdminSinPrivacyRoute: DashboardAdminSinPrivacyRoute,
  DashboardAdminSinReportingRoute: DashboardAdminSinReportingRoute,
  DashboardAdminSinSecurityRoute: DashboardAdminSinSecurityRoute,
  DashboardAdminSinIndexRoute: DashboardAdminSinIndexRoute,
};

const DashboardAdminSinRouteWithChildren =
  DashboardAdminSinRoute._addFileChildren(DashboardAdminSinRouteChildren);

interface DashboardAdminRouteRouteChildren {
  DashboardAdminRolesRoute: typeof DashboardAdminRolesRoute;
  DashboardAdminSinRoute: typeof DashboardAdminSinRouteWithChildren;
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute;
}

const DashboardAdminRouteRouteChildren: DashboardAdminRouteRouteChildren = {
  DashboardAdminRolesRoute: DashboardAdminRolesRoute,
  DashboardAdminSinRoute: DashboardAdminSinRouteWithChildren,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
};

const DashboardAdminRouteRouteWithChildren =
  DashboardAdminRouteRoute._addFileChildren(DashboardAdminRouteRouteChildren);

interface DashboardEventsSlugRouteChildren {
  DashboardEventsSlugRegisterRoute: typeof DashboardEventsSlugRegisterRoute;
  DashboardEventsSlugIndexRoute: typeof DashboardEventsSlugIndexRoute;
}

const DashboardEventsSlugRouteChildren: DashboardEventsSlugRouteChildren = {
  DashboardEventsSlugRegisterRoute: DashboardEventsSlugRegisterRoute,
  DashboardEventsSlugIndexRoute: DashboardEventsSlugIndexRoute,
};

const DashboardEventsSlugRouteWithChildren =
  DashboardEventsSlugRoute._addFileChildren(DashboardEventsSlugRouteChildren);

interface DashboardEventsRouteChildren {
  DashboardEventsSlugRoute: typeof DashboardEventsSlugRouteWithChildren;
  DashboardEventsCreateRoute: typeof DashboardEventsCreateRoute;
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute;
  DashboardEventsEventIdManageRoute: typeof DashboardEventsEventIdManageRoute;
}

const DashboardEventsRouteChildren: DashboardEventsRouteChildren = {
  DashboardEventsSlugRoute: DashboardEventsSlugRouteWithChildren,
  DashboardEventsCreateRoute: DashboardEventsCreateRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
  DashboardEventsEventIdManageRoute: DashboardEventsEventIdManageRoute,
};

const DashboardEventsRouteWithChildren = DashboardEventsRoute._addFileChildren(
  DashboardEventsRouteChildren,
);

interface DashboardSinFormsRouteChildren {
  DashboardSinFormsFormIdRoute: typeof DashboardSinFormsFormIdRoute;
}

const DashboardSinFormsRouteChildren: DashboardSinFormsRouteChildren = {
  DashboardSinFormsFormIdRoute: DashboardSinFormsFormIdRoute,
};

const DashboardSinFormsRouteWithChildren =
  DashboardSinFormsRoute._addFileChildren(DashboardSinFormsRouteChildren);

interface DashboardSinRouteChildren {
  DashboardSinAnalyticsRoute: typeof DashboardSinAnalyticsRoute;
  DashboardSinFormsRoute: typeof DashboardSinFormsRouteWithChildren;
  DashboardSinImportsRoute: typeof DashboardSinImportsRoute;
  DashboardSinReportingRoute: typeof DashboardSinReportingRoute;
  DashboardSinIndexRoute: typeof DashboardSinIndexRoute;
  DashboardSinSubmissionsSubmissionIdRoute: typeof DashboardSinSubmissionsSubmissionIdRoute;
}

const DashboardSinRouteChildren: DashboardSinRouteChildren = {
  DashboardSinAnalyticsRoute: DashboardSinAnalyticsRoute,
  DashboardSinFormsRoute: DashboardSinFormsRouteWithChildren,
  DashboardSinImportsRoute: DashboardSinImportsRoute,
  DashboardSinReportingRoute: DashboardSinReportingRoute,
  DashboardSinIndexRoute: DashboardSinIndexRoute,
  DashboardSinSubmissionsSubmissionIdRoute:
    DashboardSinSubmissionsSubmissionIdRoute,
};

const DashboardSinRouteWithChildren = DashboardSinRoute._addFileChildren(
  DashboardSinRouteChildren,
);

interface DashboardTeamsTeamIdRouteChildren {
  DashboardTeamsTeamIdManageRoute: typeof DashboardTeamsTeamIdManageRoute;
  DashboardTeamsTeamIdMembersRoute: typeof DashboardTeamsTeamIdMembersRoute;
  DashboardTeamsTeamIdIndexRoute: typeof DashboardTeamsTeamIdIndexRoute;
}

const DashboardTeamsTeamIdRouteChildren: DashboardTeamsTeamIdRouteChildren = {
  DashboardTeamsTeamIdManageRoute: DashboardTeamsTeamIdManageRoute,
  DashboardTeamsTeamIdMembersRoute: DashboardTeamsTeamIdMembersRoute,
  DashboardTeamsTeamIdIndexRoute: DashboardTeamsTeamIdIndexRoute,
};

const DashboardTeamsTeamIdRouteWithChildren =
  DashboardTeamsTeamIdRoute._addFileChildren(DashboardTeamsTeamIdRouteChildren);

interface DashboardTeamsRouteChildren {
  DashboardTeamsTeamIdRoute: typeof DashboardTeamsTeamIdRouteWithChildren;
  DashboardTeamsBrowseRoute: typeof DashboardTeamsBrowseRoute;
  DashboardTeamsCreateRoute: typeof DashboardTeamsCreateRoute;
  DashboardTeamsIndexRoute: typeof DashboardTeamsIndexRoute;
}

const DashboardTeamsRouteChildren: DashboardTeamsRouteChildren = {
  DashboardTeamsTeamIdRoute: DashboardTeamsTeamIdRouteWithChildren,
  DashboardTeamsBrowseRoute: DashboardTeamsBrowseRoute,
  DashboardTeamsCreateRoute: DashboardTeamsCreateRoute,
  DashboardTeamsIndexRoute: DashboardTeamsIndexRoute,
};

const DashboardTeamsRouteWithChildren = DashboardTeamsRoute._addFileChildren(
  DashboardTeamsRouteChildren,
);

interface DashboardRouteRouteChildren {
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRouteWithChildren;
  DashboardEventsRoute: typeof DashboardEventsRouteWithChildren;
  DashboardForbiddenRoute: typeof DashboardForbiddenRoute;
  DashboardMembersRoute: typeof DashboardMembersRoute;
  DashboardMembershipRoute: typeof DashboardMembershipRoute;
  DashboardPrivacyRoute: typeof DashboardPrivacyRoute;
  DashboardProfileRoute: typeof DashboardProfileRoute;
  DashboardReportsRoute: typeof DashboardReportsRoute;
  DashboardSelectOrgRoute: typeof DashboardSelectOrgRoute;
  DashboardSettingsRoute: typeof DashboardSettingsRoute;
  DashboardSinRoute: typeof DashboardSinRouteWithChildren;
  DashboardTeamsRoute: typeof DashboardTeamsRouteWithChildren;
  DashboardIndexRoute: typeof DashboardIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminRouteRoute: DashboardAdminRouteRouteWithChildren,
  DashboardEventsRoute: DashboardEventsRouteWithChildren,
  DashboardForbiddenRoute: DashboardForbiddenRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardMembershipRoute: DashboardMembershipRoute,
  DashboardPrivacyRoute: DashboardPrivacyRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSelectOrgRoute: DashboardSelectOrgRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSinRoute: DashboardSinRouteWithChildren,
  DashboardTeamsRoute: DashboardTeamsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

interface OnboardingRouteRouteChildren {
  OnboardingIndexRoute: typeof OnboardingIndexRoute;
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingIndexRoute: OnboardingIndexRoute,
};

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  AdminRolesRoute: AdminRolesRoute,
  ApiDebugSquareRoute: ApiDebugSquareRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiTestSquareRoute: ApiTestSquareRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTestCleanupRoute: ApiTestCleanupRoute,
  ApiWebhooksSquareRoute: ApiWebhooksSquareRoute,
  ApiAuthActionProviderRoute: ApiAuthActionProviderRoute,
  ApiPaymentsSquareCallbackRoute: ApiPaymentsSquareCallbackRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
