/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as OnboardingRouteRouteImport } from "./routes/onboarding/route";
import { Route as DashboardRouteRouteImport } from "./routes/dashboard/route";
import { Route as AuthRouteRouteImport } from "./routes/auth/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as OnboardingIndexRouteImport } from "./routes/onboarding/index";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as DashboardTeamsRouteImport } from "./routes/dashboard/teams";
import { Route as DashboardSettingsRouteImport } from "./routes/dashboard/settings";
import { Route as DashboardReportsRouteImport } from "./routes/dashboard/reports";
import { Route as DashboardProfileRouteImport } from "./routes/dashboard/profile";
import { Route as DashboardMembershipRouteImport } from "./routes/dashboard/membership";
import { Route as DashboardMembersRouteImport } from "./routes/dashboard/members";
import { Route as DashboardForbiddenRouteImport } from "./routes/dashboard/forbidden";
import { Route as DashboardEventsRouteImport } from "./routes/dashboard/events";
import { Route as AuthSignupRouteImport } from "./routes/auth/signup";
import { Route as AuthLoginRouteImport } from "./routes/auth/login";
import { Route as ApiTestSquareRouteImport } from "./routes/api/test-square";
import { Route as ApiHealthRouteImport } from "./routes/api/health";
import { Route as ApiDebugSquareRouteImport } from "./routes/api/debug-square";
import { Route as AdminRolesRouteImport } from "./routes/admin/roles";
import { Route as DashboardAdminRouteRouteImport } from "./routes/dashboard/admin/route";
import { Route as DashboardTeamsIndexRouteImport } from "./routes/dashboard/teams/index";
import { Route as DashboardEventsIndexRouteImport } from "./routes/dashboard/events/index";
import { Route as DashboardTeamsCreateRouteImport } from "./routes/dashboard/teams/create";
import { Route as DashboardTeamsBrowseRouteImport } from "./routes/dashboard/teams/browse";
import { Route as DashboardTeamsTeamIdRouteImport } from "./routes/dashboard/teams/$teamId";
import { Route as DashboardEventsCreateRouteImport } from "./routes/dashboard/events/create";
import { Route as DashboardEventsSlugRouteImport } from "./routes/dashboard/events/$slug";
import { Route as DashboardAdminRolesRouteImport } from "./routes/dashboard/admin/roles";
import { Route as ApiWebhooksSquareRouteImport } from "./routes/api/webhooks/square";
import { Route as ApiTestCleanupRouteImport } from "./routes/api/test/cleanup";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as DashboardTeamsTeamIdIndexRouteImport } from "./routes/dashboard/teams/$teamId.index";
import { Route as DashboardEventsSlugIndexRouteImport } from "./routes/dashboard/events/$slug.index";
import { Route as DashboardTeamsTeamIdMembersRouteImport } from "./routes/dashboard/teams/$teamId.members";
import { Route as DashboardTeamsTeamIdManageRouteImport } from "./routes/dashboard/teams/$teamId.manage";
import { Route as DashboardEventsSlugRegisterRouteImport } from "./routes/dashboard/events/$slug.register";
import { Route as DashboardEventsEventIdManageRouteImport } from "./routes/dashboard/events/$eventId.manage";
import { Route as ApiPaymentsSquareCallbackRouteImport } from "./routes/api/payments/square/callback";
import { Route as ApiAuthActionProviderRouteImport } from "./routes/api/auth/$action/$provider";

const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => OnboardingRouteRoute,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardTeamsRoute = DashboardTeamsRouteImport.update({
  id: "/teams",
  path: "/teams",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardMembershipRoute = DashboardMembershipRouteImport.update({
  id: "/membership",
  path: "/membership",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: "/members",
  path: "/members",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardForbiddenRoute = DashboardForbiddenRouteImport.update({
  id: "/forbidden",
  path: "/forbidden",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: "/events",
  path: "/events",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRouteRoute,
} as any);
const ApiTestSquareRoute = ApiTestSquareRouteImport.update({
  id: "/api/test-square",
  path: "/api/test-square",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: "/api/health",
  path: "/api/health",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiDebugSquareRoute = ApiDebugSquareRouteImport.update({
  id: "/api/debug-square",
  path: "/api/debug-square",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: "/admin/roles",
  path: "/admin/roles",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardTeamsIndexRoute = DashboardTeamsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardTeamsRoute,
} as any);
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardEventsRoute,
} as any);
const DashboardTeamsCreateRoute = DashboardTeamsCreateRouteImport.update({
  id: "/create",
  path: "/create",
  getParentRoute: () => DashboardTeamsRoute,
} as any);
const DashboardTeamsBrowseRoute = DashboardTeamsBrowseRouteImport.update({
  id: "/browse",
  path: "/browse",
  getParentRoute: () => DashboardTeamsRoute,
} as any);
const DashboardTeamsTeamIdRoute = DashboardTeamsTeamIdRouteImport.update({
  id: "/$teamId",
  path: "/$teamId",
  getParentRoute: () => DashboardTeamsRoute,
} as any);
const DashboardEventsCreateRoute = DashboardEventsCreateRouteImport.update({
  id: "/create",
  path: "/create",
  getParentRoute: () => DashboardEventsRoute,
} as any);
const DashboardEventsSlugRoute = DashboardEventsSlugRouteImport.update({
  id: "/$slug",
  path: "/$slug",
  getParentRoute: () => DashboardEventsRoute,
} as any);
const DashboardAdminRolesRoute = DashboardAdminRolesRouteImport.update({
  id: "/roles",
  path: "/roles",
  getParentRoute: () => DashboardAdminRouteRoute,
} as any);
const ApiWebhooksSquareRoute = ApiWebhooksSquareRouteImport.update({
  id: "/api/webhooks/square",
  path: "/api/webhooks/square",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiTestCleanupRoute = ApiTestCleanupRouteImport.update({
  id: "/api/test/cleanup",
  path: "/api/test/cleanup",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardTeamsTeamIdIndexRoute =
  DashboardTeamsTeamIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => DashboardTeamsTeamIdRoute,
  } as any);
const DashboardEventsSlugIndexRoute =
  DashboardEventsSlugIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => DashboardEventsSlugRoute,
  } as any);
const DashboardTeamsTeamIdMembersRoute =
  DashboardTeamsTeamIdMembersRouteImport.update({
    id: "/members",
    path: "/members",
    getParentRoute: () => DashboardTeamsTeamIdRoute,
  } as any);
const DashboardTeamsTeamIdManageRoute =
  DashboardTeamsTeamIdManageRouteImport.update({
    id: "/manage",
    path: "/manage",
    getParentRoute: () => DashboardTeamsTeamIdRoute,
  } as any);
const DashboardEventsSlugRegisterRoute =
  DashboardEventsSlugRegisterRouteImport.update({
    id: "/register",
    path: "/register",
    getParentRoute: () => DashboardEventsSlugRoute,
  } as any);
const DashboardEventsEventIdManageRoute =
  DashboardEventsEventIdManageRouteImport.update({
    id: "/$eventId/manage",
    path: "/$eventId/manage",
    getParentRoute: () => DashboardEventsRoute,
  } as any);
const ApiPaymentsSquareCallbackRoute =
  ApiPaymentsSquareCallbackRouteImport.update({
    id: "/api/payments/square/callback",
    path: "/api/payments/square/callback",
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiAuthActionProviderRoute = ApiAuthActionProviderRouteImport.update({
  id: "/api/auth/$action/$provider",
  path: "/api/auth/$action/$provider",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/onboarding": typeof OnboardingRouteRouteWithChildren;
  "/dashboard/admin": typeof DashboardAdminRouteRouteWithChildren;
  "/admin/roles": typeof AdminRolesRoute;
  "/api/debug-square": typeof ApiDebugSquareRoute;
  "/api/health": typeof ApiHealthRoute;
  "/api/test-square": typeof ApiTestSquareRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/signup": typeof AuthSignupRoute;
  "/dashboard/events": typeof DashboardEventsRouteWithChildren;
  "/dashboard/forbidden": typeof DashboardForbiddenRoute;
  "/dashboard/members": typeof DashboardMembersRoute;
  "/dashboard/membership": typeof DashboardMembershipRoute;
  "/dashboard/profile": typeof DashboardProfileRoute;
  "/dashboard/reports": typeof DashboardReportsRoute;
  "/dashboard/settings": typeof DashboardSettingsRoute;
  "/dashboard/teams": typeof DashboardTeamsRouteWithChildren;
  "/dashboard/": typeof DashboardIndexRoute;
  "/onboarding/": typeof OnboardingIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/test/cleanup": typeof ApiTestCleanupRoute;
  "/api/webhooks/square": typeof ApiWebhooksSquareRoute;
  "/dashboard/admin/roles": typeof DashboardAdminRolesRoute;
  "/dashboard/events/$slug": typeof DashboardEventsSlugRouteWithChildren;
  "/dashboard/events/create": typeof DashboardEventsCreateRoute;
  "/dashboard/teams/$teamId": typeof DashboardTeamsTeamIdRouteWithChildren;
  "/dashboard/teams/browse": typeof DashboardTeamsBrowseRoute;
  "/dashboard/teams/create": typeof DashboardTeamsCreateRoute;
  "/dashboard/events/": typeof DashboardEventsIndexRoute;
  "/dashboard/teams/": typeof DashboardTeamsIndexRoute;
  "/api/auth/$action/$provider": typeof ApiAuthActionProviderRoute;
  "/api/payments/square/callback": typeof ApiPaymentsSquareCallbackRoute;
  "/dashboard/events/$eventId/manage": typeof DashboardEventsEventIdManageRoute;
  "/dashboard/events/$slug/register": typeof DashboardEventsSlugRegisterRoute;
  "/dashboard/teams/$teamId/manage": typeof DashboardTeamsTeamIdManageRoute;
  "/dashboard/teams/$teamId/members": typeof DashboardTeamsTeamIdMembersRoute;
  "/dashboard/events/$slug/": typeof DashboardEventsSlugIndexRoute;
  "/dashboard/teams/$teamId/": typeof DashboardTeamsTeamIdIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/dashboard/admin": typeof DashboardAdminRouteRouteWithChildren;
  "/admin/roles": typeof AdminRolesRoute;
  "/api/debug-square": typeof ApiDebugSquareRoute;
  "/api/health": typeof ApiHealthRoute;
  "/api/test-square": typeof ApiTestSquareRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/signup": typeof AuthSignupRoute;
  "/dashboard/forbidden": typeof DashboardForbiddenRoute;
  "/dashboard/members": typeof DashboardMembersRoute;
  "/dashboard/membership": typeof DashboardMembershipRoute;
  "/dashboard/profile": typeof DashboardProfileRoute;
  "/dashboard/reports": typeof DashboardReportsRoute;
  "/dashboard/settings": typeof DashboardSettingsRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/onboarding": typeof OnboardingIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/test/cleanup": typeof ApiTestCleanupRoute;
  "/api/webhooks/square": typeof ApiWebhooksSquareRoute;
  "/dashboard/admin/roles": typeof DashboardAdminRolesRoute;
  "/dashboard/events/create": typeof DashboardEventsCreateRoute;
  "/dashboard/teams/browse": typeof DashboardTeamsBrowseRoute;
  "/dashboard/teams/create": typeof DashboardTeamsCreateRoute;
  "/dashboard/events": typeof DashboardEventsIndexRoute;
  "/dashboard/teams": typeof DashboardTeamsIndexRoute;
  "/api/auth/$action/$provider": typeof ApiAuthActionProviderRoute;
  "/api/payments/square/callback": typeof ApiPaymentsSquareCallbackRoute;
  "/dashboard/events/$eventId/manage": typeof DashboardEventsEventIdManageRoute;
  "/dashboard/events/$slug/register": typeof DashboardEventsSlugRegisterRoute;
  "/dashboard/teams/$teamId/manage": typeof DashboardTeamsTeamIdManageRoute;
  "/dashboard/teams/$teamId/members": typeof DashboardTeamsTeamIdMembersRoute;
  "/dashboard/events/$slug": typeof DashboardEventsSlugIndexRoute;
  "/dashboard/teams/$teamId": typeof DashboardTeamsTeamIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/onboarding": typeof OnboardingRouteRouteWithChildren;
  "/dashboard/admin": typeof DashboardAdminRouteRouteWithChildren;
  "/admin/roles": typeof AdminRolesRoute;
  "/api/debug-square": typeof ApiDebugSquareRoute;
  "/api/health": typeof ApiHealthRoute;
  "/api/test-square": typeof ApiTestSquareRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/signup": typeof AuthSignupRoute;
  "/dashboard/events": typeof DashboardEventsRouteWithChildren;
  "/dashboard/forbidden": typeof DashboardForbiddenRoute;
  "/dashboard/members": typeof DashboardMembersRoute;
  "/dashboard/membership": typeof DashboardMembershipRoute;
  "/dashboard/profile": typeof DashboardProfileRoute;
  "/dashboard/reports": typeof DashboardReportsRoute;
  "/dashboard/settings": typeof DashboardSettingsRoute;
  "/dashboard/teams": typeof DashboardTeamsRouteWithChildren;
  "/dashboard/": typeof DashboardIndexRoute;
  "/onboarding/": typeof OnboardingIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/test/cleanup": typeof ApiTestCleanupRoute;
  "/api/webhooks/square": typeof ApiWebhooksSquareRoute;
  "/dashboard/admin/roles": typeof DashboardAdminRolesRoute;
  "/dashboard/events/$slug": typeof DashboardEventsSlugRouteWithChildren;
  "/dashboard/events/create": typeof DashboardEventsCreateRoute;
  "/dashboard/teams/$teamId": typeof DashboardTeamsTeamIdRouteWithChildren;
  "/dashboard/teams/browse": typeof DashboardTeamsBrowseRoute;
  "/dashboard/teams/create": typeof DashboardTeamsCreateRoute;
  "/dashboard/events/": typeof DashboardEventsIndexRoute;
  "/dashboard/teams/": typeof DashboardTeamsIndexRoute;
  "/api/auth/$action/$provider": typeof ApiAuthActionProviderRoute;
  "/api/payments/square/callback": typeof ApiPaymentsSquareCallbackRoute;
  "/dashboard/events/$eventId/manage": typeof DashboardEventsEventIdManageRoute;
  "/dashboard/events/$slug/register": typeof DashboardEventsSlugRegisterRoute;
  "/dashboard/teams/$teamId/manage": typeof DashboardTeamsTeamIdManageRoute;
  "/dashboard/teams/$teamId/members": typeof DashboardTeamsTeamIdMembersRoute;
  "/dashboard/events/$slug/": typeof DashboardEventsSlugIndexRoute;
  "/dashboard/teams/$teamId/": typeof DashboardTeamsTeamIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/auth"
    | "/dashboard"
    | "/onboarding"
    | "/dashboard/admin"
    | "/admin/roles"
    | "/api/debug-square"
    | "/api/health"
    | "/api/test-square"
    | "/auth/login"
    | "/auth/signup"
    | "/dashboard/events"
    | "/dashboard/forbidden"
    | "/dashboard/members"
    | "/dashboard/membership"
    | "/dashboard/profile"
    | "/dashboard/reports"
    | "/dashboard/settings"
    | "/dashboard/teams"
    | "/dashboard/"
    | "/onboarding/"
    | "/api/auth/$"
    | "/api/test/cleanup"
    | "/api/webhooks/square"
    | "/dashboard/admin/roles"
    | "/dashboard/events/$slug"
    | "/dashboard/events/create"
    | "/dashboard/teams/$teamId"
    | "/dashboard/teams/browse"
    | "/dashboard/teams/create"
    | "/dashboard/events/"
    | "/dashboard/teams/"
    | "/api/auth/$action/$provider"
    | "/api/payments/square/callback"
    | "/dashboard/events/$eventId/manage"
    | "/dashboard/events/$slug/register"
    | "/dashboard/teams/$teamId/manage"
    | "/dashboard/teams/$teamId/members"
    | "/dashboard/events/$slug/"
    | "/dashboard/teams/$teamId/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/auth"
    | "/dashboard/admin"
    | "/admin/roles"
    | "/api/debug-square"
    | "/api/health"
    | "/api/test-square"
    | "/auth/login"
    | "/auth/signup"
    | "/dashboard/forbidden"
    | "/dashboard/members"
    | "/dashboard/membership"
    | "/dashboard/profile"
    | "/dashboard/reports"
    | "/dashboard/settings"
    | "/dashboard"
    | "/onboarding"
    | "/api/auth/$"
    | "/api/test/cleanup"
    | "/api/webhooks/square"
    | "/dashboard/admin/roles"
    | "/dashboard/events/create"
    | "/dashboard/teams/browse"
    | "/dashboard/teams/create"
    | "/dashboard/events"
    | "/dashboard/teams"
    | "/api/auth/$action/$provider"
    | "/api/payments/square/callback"
    | "/dashboard/events/$eventId/manage"
    | "/dashboard/events/$slug/register"
    | "/dashboard/teams/$teamId/manage"
    | "/dashboard/teams/$teamId/members"
    | "/dashboard/events/$slug"
    | "/dashboard/teams/$teamId";
  id:
    | "__root__"
    | "/"
    | "/auth"
    | "/dashboard"
    | "/onboarding"
    | "/dashboard/admin"
    | "/admin/roles"
    | "/api/debug-square"
    | "/api/health"
    | "/api/test-square"
    | "/auth/login"
    | "/auth/signup"
    | "/dashboard/events"
    | "/dashboard/forbidden"
    | "/dashboard/members"
    | "/dashboard/membership"
    | "/dashboard/profile"
    | "/dashboard/reports"
    | "/dashboard/settings"
    | "/dashboard/teams"
    | "/dashboard/"
    | "/onboarding/"
    | "/api/auth/$"
    | "/api/test/cleanup"
    | "/api/webhooks/square"
    | "/dashboard/admin/roles"
    | "/dashboard/events/$slug"
    | "/dashboard/events/create"
    | "/dashboard/teams/$teamId"
    | "/dashboard/teams/browse"
    | "/dashboard/teams/create"
    | "/dashboard/events/"
    | "/dashboard/teams/"
    | "/api/auth/$action/$provider"
    | "/api/payments/square/callback"
    | "/dashboard/events/$eventId/manage"
    | "/dashboard/events/$slug/register"
    | "/dashboard/teams/$teamId/manage"
    | "/dashboard/teams/$teamId/members"
    | "/dashboard/events/$slug/"
    | "/dashboard/teams/$teamId/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRouteRoute: typeof AuthRouteRouteWithChildren;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren;
  AdminRolesRoute: typeof AdminRolesRoute;
  ApiDebugSquareRoute: typeof ApiDebugSquareRoute;
  ApiHealthRoute: typeof ApiHealthRoute;
  ApiTestSquareRoute: typeof ApiTestSquareRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiTestCleanupRoute: typeof ApiTestCleanupRoute;
  ApiWebhooksSquareRoute: typeof ApiWebhooksSquareRoute;
  ApiAuthActionProviderRoute: typeof ApiAuthActionProviderRoute;
  ApiPaymentsSquareCallbackRoute: typeof ApiPaymentsSquareCallbackRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/onboarding": {
      id: "/onboarding";
      path: "/onboarding";
      fullPath: "/onboarding";
      preLoaderRoute: typeof OnboardingRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth": {
      id: "/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/onboarding/": {
      id: "/onboarding/";
      path: "/";
      fullPath: "/onboarding/";
      preLoaderRoute: typeof OnboardingIndexRouteImport;
      parentRoute: typeof OnboardingRouteRoute;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/teams": {
      id: "/dashboard/teams";
      path: "/teams";
      fullPath: "/dashboard/teams";
      preLoaderRoute: typeof DashboardTeamsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings": {
      id: "/dashboard/settings";
      path: "/settings";
      fullPath: "/dashboard/settings";
      preLoaderRoute: typeof DashboardSettingsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/reports": {
      id: "/dashboard/reports";
      path: "/reports";
      fullPath: "/dashboard/reports";
      preLoaderRoute: typeof DashboardReportsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/profile": {
      id: "/dashboard/profile";
      path: "/profile";
      fullPath: "/dashboard/profile";
      preLoaderRoute: typeof DashboardProfileRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/membership": {
      id: "/dashboard/membership";
      path: "/membership";
      fullPath: "/dashboard/membership";
      preLoaderRoute: typeof DashboardMembershipRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/members": {
      id: "/dashboard/members";
      path: "/members";
      fullPath: "/dashboard/members";
      preLoaderRoute: typeof DashboardMembersRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/forbidden": {
      id: "/dashboard/forbidden";
      path: "/forbidden";
      fullPath: "/dashboard/forbidden";
      preLoaderRoute: typeof DashboardForbiddenRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/events": {
      id: "/dashboard/events";
      path: "/events";
      fullPath: "/dashboard/events";
      preLoaderRoute: typeof DashboardEventsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/auth/signup": {
      id: "/auth/signup";
      path: "/signup";
      fullPath: "/auth/signup";
      preLoaderRoute: typeof AuthSignupRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/api/test-square": {
      id: "/api/test-square";
      path: "/api/test-square";
      fullPath: "/api/test-square";
      preLoaderRoute: typeof ApiTestSquareRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/health": {
      id: "/api/health";
      path: "/api/health";
      fullPath: "/api/health";
      preLoaderRoute: typeof ApiHealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/debug-square": {
      id: "/api/debug-square";
      path: "/api/debug-square";
      fullPath: "/api/debug-square";
      preLoaderRoute: typeof ApiDebugSquareRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/roles": {
      id: "/admin/roles";
      path: "/admin/roles";
      fullPath: "/admin/roles";
      preLoaderRoute: typeof AdminRolesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/admin": {
      id: "/dashboard/admin";
      path: "/admin";
      fullPath: "/dashboard/admin";
      preLoaderRoute: typeof DashboardAdminRouteRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/teams/": {
      id: "/dashboard/teams/";
      path: "/";
      fullPath: "/dashboard/teams/";
      preLoaderRoute: typeof DashboardTeamsIndexRouteImport;
      parentRoute: typeof DashboardTeamsRoute;
    };
    "/dashboard/events/": {
      id: "/dashboard/events/";
      path: "/";
      fullPath: "/dashboard/events/";
      preLoaderRoute: typeof DashboardEventsIndexRouteImport;
      parentRoute: typeof DashboardEventsRoute;
    };
    "/dashboard/teams/create": {
      id: "/dashboard/teams/create";
      path: "/create";
      fullPath: "/dashboard/teams/create";
      preLoaderRoute: typeof DashboardTeamsCreateRouteImport;
      parentRoute: typeof DashboardTeamsRoute;
    };
    "/dashboard/teams/browse": {
      id: "/dashboard/teams/browse";
      path: "/browse";
      fullPath: "/dashboard/teams/browse";
      preLoaderRoute: typeof DashboardTeamsBrowseRouteImport;
      parentRoute: typeof DashboardTeamsRoute;
    };
    "/dashboard/teams/$teamId": {
      id: "/dashboard/teams/$teamId";
      path: "/$teamId";
      fullPath: "/dashboard/teams/$teamId";
      preLoaderRoute: typeof DashboardTeamsTeamIdRouteImport;
      parentRoute: typeof DashboardTeamsRoute;
    };
    "/dashboard/events/create": {
      id: "/dashboard/events/create";
      path: "/create";
      fullPath: "/dashboard/events/create";
      preLoaderRoute: typeof DashboardEventsCreateRouteImport;
      parentRoute: typeof DashboardEventsRoute;
    };
    "/dashboard/events/$slug": {
      id: "/dashboard/events/$slug";
      path: "/$slug";
      fullPath: "/dashboard/events/$slug";
      preLoaderRoute: typeof DashboardEventsSlugRouteImport;
      parentRoute: typeof DashboardEventsRoute;
    };
    "/dashboard/admin/roles": {
      id: "/dashboard/admin/roles";
      path: "/roles";
      fullPath: "/dashboard/admin/roles";
      preLoaderRoute: typeof DashboardAdminRolesRouteImport;
      parentRoute: typeof DashboardAdminRouteRoute;
    };
    "/api/webhooks/square": {
      id: "/api/webhooks/square";
      path: "/api/webhooks/square";
      fullPath: "/api/webhooks/square";
      preLoaderRoute: typeof ApiWebhooksSquareRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/test/cleanup": {
      id: "/api/test/cleanup";
      path: "/api/test/cleanup";
      fullPath: "/api/test/cleanup";
      preLoaderRoute: typeof ApiTestCleanupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/teams/$teamId/": {
      id: "/dashboard/teams/$teamId/";
      path: "/";
      fullPath: "/dashboard/teams/$teamId/";
      preLoaderRoute: typeof DashboardTeamsTeamIdIndexRouteImport;
      parentRoute: typeof DashboardTeamsTeamIdRoute;
    };
    "/dashboard/events/$slug/": {
      id: "/dashboard/events/$slug/";
      path: "/";
      fullPath: "/dashboard/events/$slug/";
      preLoaderRoute: typeof DashboardEventsSlugIndexRouteImport;
      parentRoute: typeof DashboardEventsSlugRoute;
    };
    "/dashboard/teams/$teamId/members": {
      id: "/dashboard/teams/$teamId/members";
      path: "/members";
      fullPath: "/dashboard/teams/$teamId/members";
      preLoaderRoute: typeof DashboardTeamsTeamIdMembersRouteImport;
      parentRoute: typeof DashboardTeamsTeamIdRoute;
    };
    "/dashboard/teams/$teamId/manage": {
      id: "/dashboard/teams/$teamId/manage";
      path: "/manage";
      fullPath: "/dashboard/teams/$teamId/manage";
      preLoaderRoute: typeof DashboardTeamsTeamIdManageRouteImport;
      parentRoute: typeof DashboardTeamsTeamIdRoute;
    };
    "/dashboard/events/$slug/register": {
      id: "/dashboard/events/$slug/register";
      path: "/register";
      fullPath: "/dashboard/events/$slug/register";
      preLoaderRoute: typeof DashboardEventsSlugRegisterRouteImport;
      parentRoute: typeof DashboardEventsSlugRoute;
    };
    "/dashboard/events/$eventId/manage": {
      id: "/dashboard/events/$eventId/manage";
      path: "/$eventId/manage";
      fullPath: "/dashboard/events/$eventId/manage";
      preLoaderRoute: typeof DashboardEventsEventIdManageRouteImport;
      parentRoute: typeof DashboardEventsRoute;
    };
    "/api/payments/square/callback": {
      id: "/api/payments/square/callback";
      path: "/api/payments/square/callback";
      fullPath: "/api/payments/square/callback";
      preLoaderRoute: typeof ApiPaymentsSquareCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$action/$provider": {
      id: "/api/auth/$action/$provider";
      path: "/api/auth/$action/$provider";
      fullPath: "/api/auth/$action/$provider";
      preLoaderRoute: typeof ApiAuthActionProviderRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthSignupRoute: typeof AuthSignupRoute;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
);

interface DashboardAdminRouteRouteChildren {
  DashboardAdminRolesRoute: typeof DashboardAdminRolesRoute;
}

const DashboardAdminRouteRouteChildren: DashboardAdminRouteRouteChildren = {
  DashboardAdminRolesRoute: DashboardAdminRolesRoute,
};

const DashboardAdminRouteRouteWithChildren =
  DashboardAdminRouteRoute._addFileChildren(DashboardAdminRouteRouteChildren);

interface DashboardEventsSlugRouteChildren {
  DashboardEventsSlugRegisterRoute: typeof DashboardEventsSlugRegisterRoute;
  DashboardEventsSlugIndexRoute: typeof DashboardEventsSlugIndexRoute;
}

const DashboardEventsSlugRouteChildren: DashboardEventsSlugRouteChildren = {
  DashboardEventsSlugRegisterRoute: DashboardEventsSlugRegisterRoute,
  DashboardEventsSlugIndexRoute: DashboardEventsSlugIndexRoute,
};

const DashboardEventsSlugRouteWithChildren =
  DashboardEventsSlugRoute._addFileChildren(DashboardEventsSlugRouteChildren);

interface DashboardEventsRouteChildren {
  DashboardEventsSlugRoute: typeof DashboardEventsSlugRouteWithChildren;
  DashboardEventsCreateRoute: typeof DashboardEventsCreateRoute;
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute;
  DashboardEventsEventIdManageRoute: typeof DashboardEventsEventIdManageRoute;
}

const DashboardEventsRouteChildren: DashboardEventsRouteChildren = {
  DashboardEventsSlugRoute: DashboardEventsSlugRouteWithChildren,
  DashboardEventsCreateRoute: DashboardEventsCreateRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
  DashboardEventsEventIdManageRoute: DashboardEventsEventIdManageRoute,
};

const DashboardEventsRouteWithChildren = DashboardEventsRoute._addFileChildren(
  DashboardEventsRouteChildren,
);

interface DashboardTeamsTeamIdRouteChildren {
  DashboardTeamsTeamIdManageRoute: typeof DashboardTeamsTeamIdManageRoute;
  DashboardTeamsTeamIdMembersRoute: typeof DashboardTeamsTeamIdMembersRoute;
  DashboardTeamsTeamIdIndexRoute: typeof DashboardTeamsTeamIdIndexRoute;
}

const DashboardTeamsTeamIdRouteChildren: DashboardTeamsTeamIdRouteChildren = {
  DashboardTeamsTeamIdManageRoute: DashboardTeamsTeamIdManageRoute,
  DashboardTeamsTeamIdMembersRoute: DashboardTeamsTeamIdMembersRoute,
  DashboardTeamsTeamIdIndexRoute: DashboardTeamsTeamIdIndexRoute,
};

const DashboardTeamsTeamIdRouteWithChildren =
  DashboardTeamsTeamIdRoute._addFileChildren(DashboardTeamsTeamIdRouteChildren);

interface DashboardTeamsRouteChildren {
  DashboardTeamsTeamIdRoute: typeof DashboardTeamsTeamIdRouteWithChildren;
  DashboardTeamsBrowseRoute: typeof DashboardTeamsBrowseRoute;
  DashboardTeamsCreateRoute: typeof DashboardTeamsCreateRoute;
  DashboardTeamsIndexRoute: typeof DashboardTeamsIndexRoute;
}

const DashboardTeamsRouteChildren: DashboardTeamsRouteChildren = {
  DashboardTeamsTeamIdRoute: DashboardTeamsTeamIdRouteWithChildren,
  DashboardTeamsBrowseRoute: DashboardTeamsBrowseRoute,
  DashboardTeamsCreateRoute: DashboardTeamsCreateRoute,
  DashboardTeamsIndexRoute: DashboardTeamsIndexRoute,
};

const DashboardTeamsRouteWithChildren = DashboardTeamsRoute._addFileChildren(
  DashboardTeamsRouteChildren,
);

interface DashboardRouteRouteChildren {
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRouteWithChildren;
  DashboardEventsRoute: typeof DashboardEventsRouteWithChildren;
  DashboardForbiddenRoute: typeof DashboardForbiddenRoute;
  DashboardMembersRoute: typeof DashboardMembersRoute;
  DashboardMembershipRoute: typeof DashboardMembershipRoute;
  DashboardProfileRoute: typeof DashboardProfileRoute;
  DashboardReportsRoute: typeof DashboardReportsRoute;
  DashboardSettingsRoute: typeof DashboardSettingsRoute;
  DashboardTeamsRoute: typeof DashboardTeamsRouteWithChildren;
  DashboardIndexRoute: typeof DashboardIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminRouteRoute: DashboardAdminRouteRouteWithChildren,
  DashboardEventsRoute: DashboardEventsRouteWithChildren,
  DashboardForbiddenRoute: DashboardForbiddenRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardMembershipRoute: DashboardMembershipRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTeamsRoute: DashboardTeamsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

interface OnboardingRouteRouteChildren {
  OnboardingIndexRoute: typeof OnboardingIndexRoute;
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingIndexRoute: OnboardingIndexRoute,
};

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  AdminRolesRoute: AdminRolesRoute,
  ApiDebugSquareRoute: ApiDebugSquareRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiTestSquareRoute: ApiTestSquareRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTestCleanupRoute: ApiTestCleanupRoute,
  ApiWebhooksSquareRoute: ApiWebhooksSquareRoute,
  ApiAuthActionProviderRoute: ApiAuthActionProviderRoute,
  ApiPaymentsSquareCallbackRoute: ApiPaymentsSquareCallbackRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
