/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from "@tanstack/react-start/server";

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SearchRouteImport } from "./routes/search";
import { Route as EventsRouteImport } from "./routes/events";
import { Route as OnboardingRouteRouteImport } from "./routes/onboarding/route";
import { Route as DashboardRouteRouteImport } from "./routes/dashboard/route";
import { Route as AuthRouteRouteImport } from "./routes/auth/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as OnboardingIndexRouteImport } from "./routes/onboarding/index";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as GameGameIdRouteImport } from "./routes/game.$gameId";
import { Route as EventEventIdRouteImport } from "./routes/event.$eventId";
import { Route as DashboardTeamsRouteImport } from "./routes/dashboard/teams";
import { Route as DashboardSettingsRouteImport } from "./routes/dashboard/settings";
import { Route as DashboardReportsRouteImport } from "./routes/dashboard/reports";
import { Route as DashboardProfileRouteImport } from "./routes/dashboard/profile";
import { Route as DashboardMembershipRouteImport } from "./routes/dashboard/membership";
import { Route as DashboardMembersRouteImport } from "./routes/dashboard/members";
import { Route as DashboardGamesRouteImport } from "./routes/dashboard/games";
import { Route as DashboardEventsRouteImport } from "./routes/dashboard/events";
import { Route as DashboardCampaignsRouteImport } from "./routes/dashboard/campaigns";
import { Route as AuthSignupRouteImport } from "./routes/auth/signup";
import { Route as AuthResetPasswordRouteImport } from "./routes/auth/reset-password";
import { Route as AuthLoginRouteImport } from "./routes/auth/login";
import { Route as AuthForgotPasswordRouteImport } from "./routes/auth/forgot-password";
import { Route as DashboardTeamsIndexRouteImport } from "./routes/dashboard/teams/index";
import { Route as DashboardProfileIndexRouteImport } from "./routes/dashboard/profile/index";
import { Route as DashboardGamesIndexRouteImport } from "./routes/dashboard/games/index";
import { Route as DashboardEventsIndexRouteImport } from "./routes/dashboard/events/index";
import { Route as DashboardCampaignsIndexRouteImport } from "./routes/dashboard/campaigns/index";
import { Route as DashboardTeamsCreateRouteImport } from "./routes/dashboard/teams/create";
import { Route as DashboardTeamsBrowseRouteImport } from "./routes/dashboard/teams/browse";
import { Route as DashboardTeamsTeamIdRouteImport } from "./routes/dashboard/teams/$teamId";
import { Route as DashboardProfileUserIdRouteImport } from "./routes/dashboard/profile/$userId";
import { Route as DashboardGamesCreateRouteImport } from "./routes/dashboard/games/create";
import { Route as DashboardGamesGameIdRouteImport } from "./routes/dashboard/games/$gameId";
import { Route as DashboardEventsCreateRouteImport } from "./routes/dashboard/events/create";
import { Route as DashboardEventsEventIdRouteImport } from "./routes/dashboard/events/$eventId";
import { Route as DashboardCampaignsCreateRouteImport } from "./routes/dashboard/campaigns/create";
import { Route as DashboardCampaignsCampaignIdRouteImport } from "./routes/dashboard/campaigns/$campaignId";
import { Route as DashboardTeamsTeamIdIndexRouteImport } from "./routes/dashboard/teams/$teamId.index";
import { Route as DashboardCampaignsCampaignIdIndexRouteImport } from "./routes/dashboard/campaigns/$campaignId/index";
import { Route as DashboardTeamsTeamIdMembersRouteImport } from "./routes/dashboard/teams/$teamId.members";
import { Route as DashboardTeamsTeamIdManageRouteImport } from "./routes/dashboard/teams/$teamId.manage";
import { Route as DashboardCampaignsCampaignIdZeroRouteImport } from "./routes/dashboard/campaigns/$campaignId/zero";
import { ServerRoute as ApiHealthServerRouteImport } from "./routes/api/health";
import { ServerRoute as ApiWebhooksSquareServerRouteImport } from "./routes/api/webhooks/square";
import { ServerRoute as ApiTestCleanupServerRouteImport } from "./routes/api/test/cleanup";
import { ServerRoute as ApiSocialUnfollowServerRouteImport } from "./routes/api/social/unfollow";
import { ServerRoute as ApiSocialUnblockServerRouteImport } from "./routes/api/social/unblock";
import { ServerRoute as ApiSocialRelationshipServerRouteImport } from "./routes/api/social/relationship";
import { ServerRoute as ApiSocialFollowServerRouteImport } from "./routes/api/social/follow";
import { ServerRoute as ApiSocialBlocklistServerRouteImport } from "./routes/api/social/blocklist";
import { ServerRoute as ApiSocialBlockServerRouteImport } from "./routes/api/social/block";
import { ServerRoute as ApiAuthSplatServerRouteImport } from "./routes/api/auth/$";
import { ServerRoute as ApiPaymentsSquareCallbackServerRouteImport } from "./routes/api/payments/square/callback";
import { ServerRoute as ApiAuthActionProviderServerRouteImport } from "./routes/api/auth/$action/$provider";

const rootServerRouteImport = createServerRootRoute();

const SearchRoute = SearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => rootRouteImport,
} as any);
const EventsRoute = EventsRouteImport.update({
  id: "/events",
  path: "/events",
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => OnboardingRouteRoute,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: "/game/$gameId",
  path: "/game/$gameId",
  getParentRoute: () => rootRouteImport,
} as any);
const EventEventIdRoute = EventEventIdRouteImport.update({
  id: "/event/$eventId",
  path: "/event/$eventId",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardTeamsRoute = DashboardTeamsRouteImport.update({
  id: "/teams",
  path: "/teams",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardMembershipRoute = DashboardMembershipRouteImport.update({
  id: "/membership",
  path: "/membership",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: "/members",
  path: "/members",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardGamesRoute = DashboardGamesRouteImport.update({
  id: "/games",
  path: "/games",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: "/events",
  path: "/events",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardCampaignsRoute = DashboardCampaignsRouteImport.update({
  id: "/campaigns",
  path: "/campaigns",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => AuthRouteRoute,
} as any);
const DashboardTeamsIndexRoute = DashboardTeamsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardTeamsRoute,
} as any);
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardProfileRoute,
} as any);
const DashboardGamesIndexRoute = DashboardGamesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardGamesRoute,
} as any);
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardEventsRoute,
} as any);
const DashboardCampaignsIndexRoute = DashboardCampaignsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardCampaignsRoute,
} as any);
const DashboardTeamsCreateRoute = DashboardTeamsCreateRouteImport.update({
  id: "/create",
  path: "/create",
  getParentRoute: () => DashboardTeamsRoute,
} as any);
const DashboardTeamsBrowseRoute = DashboardTeamsBrowseRouteImport.update({
  id: "/browse",
  path: "/browse",
  getParentRoute: () => DashboardTeamsRoute,
} as any);
const DashboardTeamsTeamIdRoute = DashboardTeamsTeamIdRouteImport.update({
  id: "/$teamId",
  path: "/$teamId",
  getParentRoute: () => DashboardTeamsRoute,
} as any);
const DashboardProfileUserIdRoute = DashboardProfileUserIdRouteImport.update({
  id: "/$userId",
  path: "/$userId",
  getParentRoute: () => DashboardProfileRoute,
} as any);
const DashboardGamesCreateRoute = DashboardGamesCreateRouteImport.update({
  id: "/create",
  path: "/create",
  getParentRoute: () => DashboardGamesRoute,
} as any);
const DashboardGamesGameIdRoute = DashboardGamesGameIdRouteImport.update({
  id: "/$gameId",
  path: "/$gameId",
  getParentRoute: () => DashboardGamesRoute,
} as any);
const DashboardEventsCreateRoute = DashboardEventsCreateRouteImport.update({
  id: "/create",
  path: "/create",
  getParentRoute: () => DashboardEventsRoute,
} as any);
const DashboardEventsEventIdRoute = DashboardEventsEventIdRouteImport.update({
  id: "/$eventId",
  path: "/$eventId",
  getParentRoute: () => DashboardEventsRoute,
} as any);
const DashboardCampaignsCreateRoute =
  DashboardCampaignsCreateRouteImport.update({
    id: "/create",
    path: "/create",
    getParentRoute: () => DashboardCampaignsRoute,
  } as any);
const DashboardCampaignsCampaignIdRoute =
  DashboardCampaignsCampaignIdRouteImport.update({
    id: "/$campaignId",
    path: "/$campaignId",
    getParentRoute: () => DashboardCampaignsRoute,
  } as any);
const DashboardTeamsTeamIdIndexRoute =
  DashboardTeamsTeamIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => DashboardTeamsTeamIdRoute,
  } as any);
const DashboardCampaignsCampaignIdIndexRoute =
  DashboardCampaignsCampaignIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => DashboardCampaignsCampaignIdRoute,
  } as any);
const DashboardTeamsTeamIdMembersRoute =
  DashboardTeamsTeamIdMembersRouteImport.update({
    id: "/members",
    path: "/members",
    getParentRoute: () => DashboardTeamsTeamIdRoute,
  } as any);
const DashboardTeamsTeamIdManageRoute =
  DashboardTeamsTeamIdManageRouteImport.update({
    id: "/manage",
    path: "/manage",
    getParentRoute: () => DashboardTeamsTeamIdRoute,
  } as any);
const DashboardCampaignsCampaignIdZeroRoute =
  DashboardCampaignsCampaignIdZeroRouteImport.update({
    id: "/zero",
    path: "/zero",
    getParentRoute: () => DashboardCampaignsCampaignIdRoute,
  } as any);
const ApiHealthServerRoute = ApiHealthServerRouteImport.update({
  id: "/api/health",
  path: "/api/health",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiWebhooksSquareServerRoute = ApiWebhooksSquareServerRouteImport.update({
  id: "/api/webhooks/square",
  path: "/api/webhooks/square",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiTestCleanupServerRoute = ApiTestCleanupServerRouteImport.update({
  id: "/api/test/cleanup",
  path: "/api/test/cleanup",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiSocialUnfollowServerRoute = ApiSocialUnfollowServerRouteImport.update({
  id: "/api/social/unfollow",
  path: "/api/social/unfollow",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiSocialUnblockServerRoute = ApiSocialUnblockServerRouteImport.update({
  id: "/api/social/unblock",
  path: "/api/social/unblock",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiSocialRelationshipServerRoute =
  ApiSocialRelationshipServerRouteImport.update({
    id: "/api/social/relationship",
    path: "/api/social/relationship",
    getParentRoute: () => rootServerRouteImport,
  } as any);
const ApiSocialFollowServerRoute = ApiSocialFollowServerRouteImport.update({
  id: "/api/social/follow",
  path: "/api/social/follow",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiSocialBlocklistServerRoute =
  ApiSocialBlocklistServerRouteImport.update({
    id: "/api/social/blocklist",
    path: "/api/social/blocklist",
    getParentRoute: () => rootServerRouteImport,
  } as any);
const ApiSocialBlockServerRoute = ApiSocialBlockServerRouteImport.update({
  id: "/api/social/block",
  path: "/api/social/block",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiPaymentsSquareCallbackServerRoute =
  ApiPaymentsSquareCallbackServerRouteImport.update({
    id: "/api/payments/square/callback",
    path: "/api/payments/square/callback",
    getParentRoute: () => rootServerRouteImport,
  } as any);
const ApiAuthActionProviderServerRoute =
  ApiAuthActionProviderServerRouteImport.update({
    id: "/api/auth/$action/$provider",
    path: "/api/auth/$action/$provider",
    getParentRoute: () => rootServerRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/onboarding": typeof OnboardingRouteRouteWithChildren;
  "/events": typeof EventsRoute;
  "/search": typeof SearchRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/signup": typeof AuthSignupRoute;
  "/dashboard/campaigns": typeof DashboardCampaignsRouteWithChildren;
  "/dashboard/events": typeof DashboardEventsRouteWithChildren;
  "/dashboard/games": typeof DashboardGamesRouteWithChildren;
  "/dashboard/members": typeof DashboardMembersRoute;
  "/dashboard/membership": typeof DashboardMembershipRoute;
  "/dashboard/profile": typeof DashboardProfileRouteWithChildren;
  "/dashboard/reports": typeof DashboardReportsRoute;
  "/dashboard/settings": typeof DashboardSettingsRoute;
  "/dashboard/teams": typeof DashboardTeamsRouteWithChildren;
  "/event/$eventId": typeof EventEventIdRoute;
  "/game/$gameId": typeof GameGameIdRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/onboarding/": typeof OnboardingIndexRoute;
  "/dashboard/campaigns/$campaignId": typeof DashboardCampaignsCampaignIdRouteWithChildren;
  "/dashboard/campaigns/create": typeof DashboardCampaignsCreateRoute;
  "/dashboard/events/$eventId": typeof DashboardEventsEventIdRoute;
  "/dashboard/events/create": typeof DashboardEventsCreateRoute;
  "/dashboard/games/$gameId": typeof DashboardGamesGameIdRoute;
  "/dashboard/games/create": typeof DashboardGamesCreateRoute;
  "/dashboard/profile/$userId": typeof DashboardProfileUserIdRoute;
  "/dashboard/teams/$teamId": typeof DashboardTeamsTeamIdRouteWithChildren;
  "/dashboard/teams/browse": typeof DashboardTeamsBrowseRoute;
  "/dashboard/teams/create": typeof DashboardTeamsCreateRoute;
  "/dashboard/campaigns/": typeof DashboardCampaignsIndexRoute;
  "/dashboard/events/": typeof DashboardEventsIndexRoute;
  "/dashboard/games/": typeof DashboardGamesIndexRoute;
  "/dashboard/profile/": typeof DashboardProfileIndexRoute;
  "/dashboard/teams/": typeof DashboardTeamsIndexRoute;
  "/dashboard/campaigns/$campaignId/zero": typeof DashboardCampaignsCampaignIdZeroRoute;
  "/dashboard/teams/$teamId/manage": typeof DashboardTeamsTeamIdManageRoute;
  "/dashboard/teams/$teamId/members": typeof DashboardTeamsTeamIdMembersRoute;
  "/dashboard/campaigns/$campaignId/": typeof DashboardCampaignsCampaignIdIndexRoute;
  "/dashboard/teams/$teamId/": typeof DashboardTeamsTeamIdIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/events": typeof EventsRoute;
  "/search": typeof SearchRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/signup": typeof AuthSignupRoute;
  "/dashboard/members": typeof DashboardMembersRoute;
  "/dashboard/membership": typeof DashboardMembershipRoute;
  "/dashboard/reports": typeof DashboardReportsRoute;
  "/dashboard/settings": typeof DashboardSettingsRoute;
  "/event/$eventId": typeof EventEventIdRoute;
  "/game/$gameId": typeof GameGameIdRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/onboarding": typeof OnboardingIndexRoute;
  "/dashboard/campaigns/create": typeof DashboardCampaignsCreateRoute;
  "/dashboard/events/$eventId": typeof DashboardEventsEventIdRoute;
  "/dashboard/events/create": typeof DashboardEventsCreateRoute;
  "/dashboard/games/$gameId": typeof DashboardGamesGameIdRoute;
  "/dashboard/games/create": typeof DashboardGamesCreateRoute;
  "/dashboard/profile/$userId": typeof DashboardProfileUserIdRoute;
  "/dashboard/teams/browse": typeof DashboardTeamsBrowseRoute;
  "/dashboard/teams/create": typeof DashboardTeamsCreateRoute;
  "/dashboard/campaigns": typeof DashboardCampaignsIndexRoute;
  "/dashboard/events": typeof DashboardEventsIndexRoute;
  "/dashboard/games": typeof DashboardGamesIndexRoute;
  "/dashboard/profile": typeof DashboardProfileIndexRoute;
  "/dashboard/teams": typeof DashboardTeamsIndexRoute;
  "/dashboard/campaigns/$campaignId/zero": typeof DashboardCampaignsCampaignIdZeroRoute;
  "/dashboard/teams/$teamId/manage": typeof DashboardTeamsTeamIdManageRoute;
  "/dashboard/teams/$teamId/members": typeof DashboardTeamsTeamIdMembersRoute;
  "/dashboard/campaigns/$campaignId": typeof DashboardCampaignsCampaignIdIndexRoute;
  "/dashboard/teams/$teamId": typeof DashboardTeamsTeamIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/onboarding": typeof OnboardingRouteRouteWithChildren;
  "/events": typeof EventsRoute;
  "/search": typeof SearchRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/signup": typeof AuthSignupRoute;
  "/dashboard/campaigns": typeof DashboardCampaignsRouteWithChildren;
  "/dashboard/events": typeof DashboardEventsRouteWithChildren;
  "/dashboard/games": typeof DashboardGamesRouteWithChildren;
  "/dashboard/members": typeof DashboardMembersRoute;
  "/dashboard/membership": typeof DashboardMembershipRoute;
  "/dashboard/profile": typeof DashboardProfileRouteWithChildren;
  "/dashboard/reports": typeof DashboardReportsRoute;
  "/dashboard/settings": typeof DashboardSettingsRoute;
  "/dashboard/teams": typeof DashboardTeamsRouteWithChildren;
  "/event/$eventId": typeof EventEventIdRoute;
  "/game/$gameId": typeof GameGameIdRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/onboarding/": typeof OnboardingIndexRoute;
  "/dashboard/campaigns/$campaignId": typeof DashboardCampaignsCampaignIdRouteWithChildren;
  "/dashboard/campaigns/create": typeof DashboardCampaignsCreateRoute;
  "/dashboard/events/$eventId": typeof DashboardEventsEventIdRoute;
  "/dashboard/events/create": typeof DashboardEventsCreateRoute;
  "/dashboard/games/$gameId": typeof DashboardGamesGameIdRoute;
  "/dashboard/games/create": typeof DashboardGamesCreateRoute;
  "/dashboard/profile/$userId": typeof DashboardProfileUserIdRoute;
  "/dashboard/teams/$teamId": typeof DashboardTeamsTeamIdRouteWithChildren;
  "/dashboard/teams/browse": typeof DashboardTeamsBrowseRoute;
  "/dashboard/teams/create": typeof DashboardTeamsCreateRoute;
  "/dashboard/campaigns/": typeof DashboardCampaignsIndexRoute;
  "/dashboard/events/": typeof DashboardEventsIndexRoute;
  "/dashboard/games/": typeof DashboardGamesIndexRoute;
  "/dashboard/profile/": typeof DashboardProfileIndexRoute;
  "/dashboard/teams/": typeof DashboardTeamsIndexRoute;
  "/dashboard/campaigns/$campaignId/zero": typeof DashboardCampaignsCampaignIdZeroRoute;
  "/dashboard/teams/$teamId/manage": typeof DashboardTeamsTeamIdManageRoute;
  "/dashboard/teams/$teamId/members": typeof DashboardTeamsTeamIdMembersRoute;
  "/dashboard/campaigns/$campaignId/": typeof DashboardCampaignsCampaignIdIndexRoute;
  "/dashboard/teams/$teamId/": typeof DashboardTeamsTeamIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/auth"
    | "/dashboard"
    | "/onboarding"
    | "/events"
    | "/search"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/reset-password"
    | "/auth/signup"
    | "/dashboard/campaigns"
    | "/dashboard/events"
    | "/dashboard/games"
    | "/dashboard/members"
    | "/dashboard/membership"
    | "/dashboard/profile"
    | "/dashboard/reports"
    | "/dashboard/settings"
    | "/dashboard/teams"
    | "/event/$eventId"
    | "/game/$gameId"
    | "/dashboard/"
    | "/onboarding/"
    | "/dashboard/campaigns/$campaignId"
    | "/dashboard/campaigns/create"
    | "/dashboard/events/$eventId"
    | "/dashboard/events/create"
    | "/dashboard/games/$gameId"
    | "/dashboard/games/create"
    | "/dashboard/profile/$userId"
    | "/dashboard/teams/$teamId"
    | "/dashboard/teams/browse"
    | "/dashboard/teams/create"
    | "/dashboard/campaigns/"
    | "/dashboard/events/"
    | "/dashboard/games/"
    | "/dashboard/profile/"
    | "/dashboard/teams/"
    | "/dashboard/campaigns/$campaignId/zero"
    | "/dashboard/teams/$teamId/manage"
    | "/dashboard/teams/$teamId/members"
    | "/dashboard/campaigns/$campaignId/"
    | "/dashboard/teams/$teamId/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/auth"
    | "/events"
    | "/search"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/reset-password"
    | "/auth/signup"
    | "/dashboard/members"
    | "/dashboard/membership"
    | "/dashboard/reports"
    | "/dashboard/settings"
    | "/event/$eventId"
    | "/game/$gameId"
    | "/dashboard"
    | "/onboarding"
    | "/dashboard/campaigns/create"
    | "/dashboard/events/$eventId"
    | "/dashboard/events/create"
    | "/dashboard/games/$gameId"
    | "/dashboard/games/create"
    | "/dashboard/profile/$userId"
    | "/dashboard/teams/browse"
    | "/dashboard/teams/create"
    | "/dashboard/campaigns"
    | "/dashboard/events"
    | "/dashboard/games"
    | "/dashboard/profile"
    | "/dashboard/teams"
    | "/dashboard/campaigns/$campaignId/zero"
    | "/dashboard/teams/$teamId/manage"
    | "/dashboard/teams/$teamId/members"
    | "/dashboard/campaigns/$campaignId"
    | "/dashboard/teams/$teamId";
  id:
    | "__root__"
    | "/"
    | "/auth"
    | "/dashboard"
    | "/onboarding"
    | "/events"
    | "/search"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/reset-password"
    | "/auth/signup"
    | "/dashboard/campaigns"
    | "/dashboard/events"
    | "/dashboard/games"
    | "/dashboard/members"
    | "/dashboard/membership"
    | "/dashboard/profile"
    | "/dashboard/reports"
    | "/dashboard/settings"
    | "/dashboard/teams"
    | "/event/$eventId"
    | "/game/$gameId"
    | "/dashboard/"
    | "/onboarding/"
    | "/dashboard/campaigns/$campaignId"
    | "/dashboard/campaigns/create"
    | "/dashboard/events/$eventId"
    | "/dashboard/events/create"
    | "/dashboard/games/$gameId"
    | "/dashboard/games/create"
    | "/dashboard/profile/$userId"
    | "/dashboard/teams/$teamId"
    | "/dashboard/teams/browse"
    | "/dashboard/teams/create"
    | "/dashboard/campaigns/"
    | "/dashboard/events/"
    | "/dashboard/games/"
    | "/dashboard/profile/"
    | "/dashboard/teams/"
    | "/dashboard/campaigns/$campaignId/zero"
    | "/dashboard/teams/$teamId/manage"
    | "/dashboard/teams/$teamId/members"
    | "/dashboard/campaigns/$campaignId/"
    | "/dashboard/teams/$teamId/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRouteRoute: typeof AuthRouteRouteWithChildren;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren;
  EventsRoute: typeof EventsRoute;
  SearchRoute: typeof SearchRoute;
  EventEventIdRoute: typeof EventEventIdRoute;
  GameGameIdRoute: typeof GameGameIdRoute;
}
export interface FileServerRoutesByFullPath {
  "/api/health": typeof ApiHealthServerRoute;
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/social/block": typeof ApiSocialBlockServerRoute;
  "/api/social/blocklist": typeof ApiSocialBlocklistServerRoute;
  "/api/social/follow": typeof ApiSocialFollowServerRoute;
  "/api/social/relationship": typeof ApiSocialRelationshipServerRoute;
  "/api/social/unblock": typeof ApiSocialUnblockServerRoute;
  "/api/social/unfollow": typeof ApiSocialUnfollowServerRoute;
  "/api/test/cleanup": typeof ApiTestCleanupServerRoute;
  "/api/webhooks/square": typeof ApiWebhooksSquareServerRoute;
  "/api/auth/$action/$provider": typeof ApiAuthActionProviderServerRoute;
  "/api/payments/square/callback": typeof ApiPaymentsSquareCallbackServerRoute;
}
export interface FileServerRoutesByTo {
  "/api/health": typeof ApiHealthServerRoute;
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/social/block": typeof ApiSocialBlockServerRoute;
  "/api/social/blocklist": typeof ApiSocialBlocklistServerRoute;
  "/api/social/follow": typeof ApiSocialFollowServerRoute;
  "/api/social/relationship": typeof ApiSocialRelationshipServerRoute;
  "/api/social/unblock": typeof ApiSocialUnblockServerRoute;
  "/api/social/unfollow": typeof ApiSocialUnfollowServerRoute;
  "/api/test/cleanup": typeof ApiTestCleanupServerRoute;
  "/api/webhooks/square": typeof ApiWebhooksSquareServerRoute;
  "/api/auth/$action/$provider": typeof ApiAuthActionProviderServerRoute;
  "/api/payments/square/callback": typeof ApiPaymentsSquareCallbackServerRoute;
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport;
  "/api/health": typeof ApiHealthServerRoute;
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/social/block": typeof ApiSocialBlockServerRoute;
  "/api/social/blocklist": typeof ApiSocialBlocklistServerRoute;
  "/api/social/follow": typeof ApiSocialFollowServerRoute;
  "/api/social/relationship": typeof ApiSocialRelationshipServerRoute;
  "/api/social/unblock": typeof ApiSocialUnblockServerRoute;
  "/api/social/unfollow": typeof ApiSocialUnfollowServerRoute;
  "/api/test/cleanup": typeof ApiTestCleanupServerRoute;
  "/api/webhooks/square": typeof ApiWebhooksSquareServerRoute;
  "/api/auth/$action/$provider": typeof ApiAuthActionProviderServerRoute;
  "/api/payments/square/callback": typeof ApiPaymentsSquareCallbackServerRoute;
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath;
  fullPaths:
    | "/api/health"
    | "/api/auth/$"
    | "/api/social/block"
    | "/api/social/blocklist"
    | "/api/social/follow"
    | "/api/social/relationship"
    | "/api/social/unblock"
    | "/api/social/unfollow"
    | "/api/test/cleanup"
    | "/api/webhooks/square"
    | "/api/auth/$action/$provider"
    | "/api/payments/square/callback";
  fileServerRoutesByTo: FileServerRoutesByTo;
  to:
    | "/api/health"
    | "/api/auth/$"
    | "/api/social/block"
    | "/api/social/blocklist"
    | "/api/social/follow"
    | "/api/social/relationship"
    | "/api/social/unblock"
    | "/api/social/unfollow"
    | "/api/test/cleanup"
    | "/api/webhooks/square"
    | "/api/auth/$action/$provider"
    | "/api/payments/square/callback";
  id:
    | "__root__"
    | "/api/health"
    | "/api/auth/$"
    | "/api/social/block"
    | "/api/social/blocklist"
    | "/api/social/follow"
    | "/api/social/relationship"
    | "/api/social/unblock"
    | "/api/social/unfollow"
    | "/api/test/cleanup"
    | "/api/webhooks/square"
    | "/api/auth/$action/$provider"
    | "/api/payments/square/callback";
  fileServerRoutesById: FileServerRoutesById;
}
export interface RootServerRouteChildren {
  ApiHealthServerRoute: typeof ApiHealthServerRoute;
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute;
  ApiSocialBlockServerRoute: typeof ApiSocialBlockServerRoute;
  ApiSocialBlocklistServerRoute: typeof ApiSocialBlocklistServerRoute;
  ApiSocialFollowServerRoute: typeof ApiSocialFollowServerRoute;
  ApiSocialRelationshipServerRoute: typeof ApiSocialRelationshipServerRoute;
  ApiSocialUnblockServerRoute: typeof ApiSocialUnblockServerRoute;
  ApiSocialUnfollowServerRoute: typeof ApiSocialUnfollowServerRoute;
  ApiTestCleanupServerRoute: typeof ApiTestCleanupServerRoute;
  ApiWebhooksSquareServerRoute: typeof ApiWebhooksSquareServerRoute;
  ApiAuthActionProviderServerRoute: typeof ApiAuthActionProviderServerRoute;
  ApiPaymentsSquareCallbackServerRoute: typeof ApiPaymentsSquareCallbackServerRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/search": {
      id: "/search";
      path: "/search";
      fullPath: "/search";
      preLoaderRoute: typeof SearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/events": {
      id: "/events";
      path: "/events";
      fullPath: "/events";
      preLoaderRoute: typeof EventsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/onboarding": {
      id: "/onboarding";
      path: "/onboarding";
      fullPath: "/onboarding";
      preLoaderRoute: typeof OnboardingRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth": {
      id: "/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/onboarding/": {
      id: "/onboarding/";
      path: "/";
      fullPath: "/onboarding/";
      preLoaderRoute: typeof OnboardingIndexRouteImport;
      parentRoute: typeof OnboardingRouteRoute;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/game/$gameId": {
      id: "/game/$gameId";
      path: "/game/$gameId";
      fullPath: "/game/$gameId";
      preLoaderRoute: typeof GameGameIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/event/$eventId": {
      id: "/event/$eventId";
      path: "/event/$eventId";
      fullPath: "/event/$eventId";
      preLoaderRoute: typeof EventEventIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/teams": {
      id: "/dashboard/teams";
      path: "/teams";
      fullPath: "/dashboard/teams";
      preLoaderRoute: typeof DashboardTeamsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings": {
      id: "/dashboard/settings";
      path: "/settings";
      fullPath: "/dashboard/settings";
      preLoaderRoute: typeof DashboardSettingsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/reports": {
      id: "/dashboard/reports";
      path: "/reports";
      fullPath: "/dashboard/reports";
      preLoaderRoute: typeof DashboardReportsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/profile": {
      id: "/dashboard/profile";
      path: "/profile";
      fullPath: "/dashboard/profile";
      preLoaderRoute: typeof DashboardProfileRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/membership": {
      id: "/dashboard/membership";
      path: "/membership";
      fullPath: "/dashboard/membership";
      preLoaderRoute: typeof DashboardMembershipRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/members": {
      id: "/dashboard/members";
      path: "/members";
      fullPath: "/dashboard/members";
      preLoaderRoute: typeof DashboardMembersRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/games": {
      id: "/dashboard/games";
      path: "/games";
      fullPath: "/dashboard/games";
      preLoaderRoute: typeof DashboardGamesRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/events": {
      id: "/dashboard/events";
      path: "/events";
      fullPath: "/dashboard/events";
      preLoaderRoute: typeof DashboardEventsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/campaigns": {
      id: "/dashboard/campaigns";
      path: "/campaigns";
      fullPath: "/dashboard/campaigns";
      preLoaderRoute: typeof DashboardCampaignsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/auth/signup": {
      id: "/auth/signup";
      path: "/signup";
      fullPath: "/auth/signup";
      preLoaderRoute: typeof AuthSignupRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/reset-password": {
      id: "/auth/reset-password";
      path: "/reset-password";
      fullPath: "/auth/reset-password";
      preLoaderRoute: typeof AuthResetPasswordRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/forgot-password": {
      id: "/auth/forgot-password";
      path: "/forgot-password";
      fullPath: "/auth/forgot-password";
      preLoaderRoute: typeof AuthForgotPasswordRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/dashboard/teams/": {
      id: "/dashboard/teams/";
      path: "/";
      fullPath: "/dashboard/teams/";
      preLoaderRoute: typeof DashboardTeamsIndexRouteImport;
      parentRoute: typeof DashboardTeamsRoute;
    };
    "/dashboard/profile/": {
      id: "/dashboard/profile/";
      path: "/";
      fullPath: "/dashboard/profile/";
      preLoaderRoute: typeof DashboardProfileIndexRouteImport;
      parentRoute: typeof DashboardProfileRoute;
    };
    "/dashboard/games/": {
      id: "/dashboard/games/";
      path: "/";
      fullPath: "/dashboard/games/";
      preLoaderRoute: typeof DashboardGamesIndexRouteImport;
      parentRoute: typeof DashboardGamesRoute;
    };
    "/dashboard/events/": {
      id: "/dashboard/events/";
      path: "/";
      fullPath: "/dashboard/events/";
      preLoaderRoute: typeof DashboardEventsIndexRouteImport;
      parentRoute: typeof DashboardEventsRoute;
    };
    "/dashboard/campaigns/": {
      id: "/dashboard/campaigns/";
      path: "/";
      fullPath: "/dashboard/campaigns/";
      preLoaderRoute: typeof DashboardCampaignsIndexRouteImport;
      parentRoute: typeof DashboardCampaignsRoute;
    };
    "/dashboard/teams/create": {
      id: "/dashboard/teams/create";
      path: "/create";
      fullPath: "/dashboard/teams/create";
      preLoaderRoute: typeof DashboardTeamsCreateRouteImport;
      parentRoute: typeof DashboardTeamsRoute;
    };
    "/dashboard/teams/browse": {
      id: "/dashboard/teams/browse";
      path: "/browse";
      fullPath: "/dashboard/teams/browse";
      preLoaderRoute: typeof DashboardTeamsBrowseRouteImport;
      parentRoute: typeof DashboardTeamsRoute;
    };
    "/dashboard/teams/$teamId": {
      id: "/dashboard/teams/$teamId";
      path: "/$teamId";
      fullPath: "/dashboard/teams/$teamId";
      preLoaderRoute: typeof DashboardTeamsTeamIdRouteImport;
      parentRoute: typeof DashboardTeamsRoute;
    };
    "/dashboard/profile/$userId": {
      id: "/dashboard/profile/$userId";
      path: "/$userId";
      fullPath: "/dashboard/profile/$userId";
      preLoaderRoute: typeof DashboardProfileUserIdRouteImport;
      parentRoute: typeof DashboardProfileRoute;
    };
    "/dashboard/games/create": {
      id: "/dashboard/games/create";
      path: "/create";
      fullPath: "/dashboard/games/create";
      preLoaderRoute: typeof DashboardGamesCreateRouteImport;
      parentRoute: typeof DashboardGamesRoute;
    };
    "/dashboard/games/$gameId": {
      id: "/dashboard/games/$gameId";
      path: "/$gameId";
      fullPath: "/dashboard/games/$gameId";
      preLoaderRoute: typeof DashboardGamesGameIdRouteImport;
      parentRoute: typeof DashboardGamesRoute;
    };
    "/dashboard/events/create": {
      id: "/dashboard/events/create";
      path: "/create";
      fullPath: "/dashboard/events/create";
      preLoaderRoute: typeof DashboardEventsCreateRouteImport;
      parentRoute: typeof DashboardEventsRoute;
    };
    "/dashboard/events/$eventId": {
      id: "/dashboard/events/$eventId";
      path: "/$eventId";
      fullPath: "/dashboard/events/$eventId";
      preLoaderRoute: typeof DashboardEventsEventIdRouteImport;
      parentRoute: typeof DashboardEventsRoute;
    };
    "/dashboard/campaigns/create": {
      id: "/dashboard/campaigns/create";
      path: "/create";
      fullPath: "/dashboard/campaigns/create";
      preLoaderRoute: typeof DashboardCampaignsCreateRouteImport;
      parentRoute: typeof DashboardCampaignsRoute;
    };
    "/dashboard/campaigns/$campaignId": {
      id: "/dashboard/campaigns/$campaignId";
      path: "/$campaignId";
      fullPath: "/dashboard/campaigns/$campaignId";
      preLoaderRoute: typeof DashboardCampaignsCampaignIdRouteImport;
      parentRoute: typeof DashboardCampaignsRoute;
    };
    "/dashboard/teams/$teamId/": {
      id: "/dashboard/teams/$teamId/";
      path: "/";
      fullPath: "/dashboard/teams/$teamId/";
      preLoaderRoute: typeof DashboardTeamsTeamIdIndexRouteImport;
      parentRoute: typeof DashboardTeamsTeamIdRoute;
    };
    "/dashboard/campaigns/$campaignId/": {
      id: "/dashboard/campaigns/$campaignId/";
      path: "/";
      fullPath: "/dashboard/campaigns/$campaignId/";
      preLoaderRoute: typeof DashboardCampaignsCampaignIdIndexRouteImport;
      parentRoute: typeof DashboardCampaignsCampaignIdRoute;
    };
    "/dashboard/teams/$teamId/members": {
      id: "/dashboard/teams/$teamId/members";
      path: "/members";
      fullPath: "/dashboard/teams/$teamId/members";
      preLoaderRoute: typeof DashboardTeamsTeamIdMembersRouteImport;
      parentRoute: typeof DashboardTeamsTeamIdRoute;
    };
    "/dashboard/teams/$teamId/manage": {
      id: "/dashboard/teams/$teamId/manage";
      path: "/manage";
      fullPath: "/dashboard/teams/$teamId/manage";
      preLoaderRoute: typeof DashboardTeamsTeamIdManageRouteImport;
      parentRoute: typeof DashboardTeamsTeamIdRoute;
    };
    "/dashboard/campaigns/$campaignId/zero": {
      id: "/dashboard/campaigns/$campaignId/zero";
      path: "/zero";
      fullPath: "/dashboard/campaigns/$campaignId/zero";
      preLoaderRoute: typeof DashboardCampaignsCampaignIdZeroRouteImport;
      parentRoute: typeof DashboardCampaignsCampaignIdRoute;
    };
  }
}
declare module "@tanstack/react-start/server" {
  interface ServerFileRoutesByPath {
    "/api/health": {
      id: "/api/health";
      path: "/api/health";
      fullPath: "/api/health";
      preLoaderRoute: typeof ApiHealthServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/webhooks/square": {
      id: "/api/webhooks/square";
      path: "/api/webhooks/square";
      fullPath: "/api/webhooks/square";
      preLoaderRoute: typeof ApiWebhooksSquareServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/test/cleanup": {
      id: "/api/test/cleanup";
      path: "/api/test/cleanup";
      fullPath: "/api/test/cleanup";
      preLoaderRoute: typeof ApiTestCleanupServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/social/unfollow": {
      id: "/api/social/unfollow";
      path: "/api/social/unfollow";
      fullPath: "/api/social/unfollow";
      preLoaderRoute: typeof ApiSocialUnfollowServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/social/unblock": {
      id: "/api/social/unblock";
      path: "/api/social/unblock";
      fullPath: "/api/social/unblock";
      preLoaderRoute: typeof ApiSocialUnblockServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/social/relationship": {
      id: "/api/social/relationship";
      path: "/api/social/relationship";
      fullPath: "/api/social/relationship";
      preLoaderRoute: typeof ApiSocialRelationshipServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/social/follow": {
      id: "/api/social/follow";
      path: "/api/social/follow";
      fullPath: "/api/social/follow";
      preLoaderRoute: typeof ApiSocialFollowServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/social/blocklist": {
      id: "/api/social/blocklist";
      path: "/api/social/blocklist";
      fullPath: "/api/social/blocklist";
      preLoaderRoute: typeof ApiSocialBlocklistServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/social/block": {
      id: "/api/social/block";
      path: "/api/social/block";
      fullPath: "/api/social/block";
      preLoaderRoute: typeof ApiSocialBlockServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/payments/square/callback": {
      id: "/api/payments/square/callback";
      path: "/api/payments/square/callback";
      fullPath: "/api/payments/square/callback";
      preLoaderRoute: typeof ApiPaymentsSquareCallbackServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/auth/$action/$provider": {
      id: "/api/auth/$action/$provider";
      path: "/api/auth/$action/$provider";
      fullPath: "/api/auth/$action/$provider";
      preLoaderRoute: typeof ApiAuthActionProviderServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute;
  AuthSignupRoute: typeof AuthSignupRoute;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
);

interface DashboardCampaignsCampaignIdRouteChildren {
  DashboardCampaignsCampaignIdZeroRoute: typeof DashboardCampaignsCampaignIdZeroRoute;
  DashboardCampaignsCampaignIdIndexRoute: typeof DashboardCampaignsCampaignIdIndexRoute;
}

const DashboardCampaignsCampaignIdRouteChildren: DashboardCampaignsCampaignIdRouteChildren =
  {
    DashboardCampaignsCampaignIdZeroRoute:
      DashboardCampaignsCampaignIdZeroRoute,
    DashboardCampaignsCampaignIdIndexRoute:
      DashboardCampaignsCampaignIdIndexRoute,
  };

const DashboardCampaignsCampaignIdRouteWithChildren =
  DashboardCampaignsCampaignIdRoute._addFileChildren(
    DashboardCampaignsCampaignIdRouteChildren,
  );

interface DashboardCampaignsRouteChildren {
  DashboardCampaignsCampaignIdRoute: typeof DashboardCampaignsCampaignIdRouteWithChildren;
  DashboardCampaignsCreateRoute: typeof DashboardCampaignsCreateRoute;
  DashboardCampaignsIndexRoute: typeof DashboardCampaignsIndexRoute;
}

const DashboardCampaignsRouteChildren: DashboardCampaignsRouteChildren = {
  DashboardCampaignsCampaignIdRoute:
    DashboardCampaignsCampaignIdRouteWithChildren,
  DashboardCampaignsCreateRoute: DashboardCampaignsCreateRoute,
  DashboardCampaignsIndexRoute: DashboardCampaignsIndexRoute,
};

const DashboardCampaignsRouteWithChildren =
  DashboardCampaignsRoute._addFileChildren(DashboardCampaignsRouteChildren);

interface DashboardEventsRouteChildren {
  DashboardEventsEventIdRoute: typeof DashboardEventsEventIdRoute;
  DashboardEventsCreateRoute: typeof DashboardEventsCreateRoute;
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute;
}

const DashboardEventsRouteChildren: DashboardEventsRouteChildren = {
  DashboardEventsEventIdRoute: DashboardEventsEventIdRoute,
  DashboardEventsCreateRoute: DashboardEventsCreateRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
};

const DashboardEventsRouteWithChildren = DashboardEventsRoute._addFileChildren(
  DashboardEventsRouteChildren,
);

interface DashboardGamesRouteChildren {
  DashboardGamesGameIdRoute: typeof DashboardGamesGameIdRoute;
  DashboardGamesCreateRoute: typeof DashboardGamesCreateRoute;
  DashboardGamesIndexRoute: typeof DashboardGamesIndexRoute;
}

const DashboardGamesRouteChildren: DashboardGamesRouteChildren = {
  DashboardGamesGameIdRoute: DashboardGamesGameIdRoute,
  DashboardGamesCreateRoute: DashboardGamesCreateRoute,
  DashboardGamesIndexRoute: DashboardGamesIndexRoute,
};

const DashboardGamesRouteWithChildren = DashboardGamesRoute._addFileChildren(
  DashboardGamesRouteChildren,
);

interface DashboardProfileRouteChildren {
  DashboardProfileUserIdRoute: typeof DashboardProfileUserIdRoute;
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute;
}

const DashboardProfileRouteChildren: DashboardProfileRouteChildren = {
  DashboardProfileUserIdRoute: DashboardProfileUserIdRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
};

const DashboardProfileRouteWithChildren =
  DashboardProfileRoute._addFileChildren(DashboardProfileRouteChildren);

interface DashboardTeamsTeamIdRouteChildren {
  DashboardTeamsTeamIdManageRoute: typeof DashboardTeamsTeamIdManageRoute;
  DashboardTeamsTeamIdMembersRoute: typeof DashboardTeamsTeamIdMembersRoute;
  DashboardTeamsTeamIdIndexRoute: typeof DashboardTeamsTeamIdIndexRoute;
}

const DashboardTeamsTeamIdRouteChildren: DashboardTeamsTeamIdRouteChildren = {
  DashboardTeamsTeamIdManageRoute: DashboardTeamsTeamIdManageRoute,
  DashboardTeamsTeamIdMembersRoute: DashboardTeamsTeamIdMembersRoute,
  DashboardTeamsTeamIdIndexRoute: DashboardTeamsTeamIdIndexRoute,
};

const DashboardTeamsTeamIdRouteWithChildren =
  DashboardTeamsTeamIdRoute._addFileChildren(DashboardTeamsTeamIdRouteChildren);

interface DashboardTeamsRouteChildren {
  DashboardTeamsTeamIdRoute: typeof DashboardTeamsTeamIdRouteWithChildren;
  DashboardTeamsBrowseRoute: typeof DashboardTeamsBrowseRoute;
  DashboardTeamsCreateRoute: typeof DashboardTeamsCreateRoute;
  DashboardTeamsIndexRoute: typeof DashboardTeamsIndexRoute;
}

const DashboardTeamsRouteChildren: DashboardTeamsRouteChildren = {
  DashboardTeamsTeamIdRoute: DashboardTeamsTeamIdRouteWithChildren,
  DashboardTeamsBrowseRoute: DashboardTeamsBrowseRoute,
  DashboardTeamsCreateRoute: DashboardTeamsCreateRoute,
  DashboardTeamsIndexRoute: DashboardTeamsIndexRoute,
};

const DashboardTeamsRouteWithChildren = DashboardTeamsRoute._addFileChildren(
  DashboardTeamsRouteChildren,
);

interface DashboardRouteRouteChildren {
  DashboardCampaignsRoute: typeof DashboardCampaignsRouteWithChildren;
  DashboardEventsRoute: typeof DashboardEventsRouteWithChildren;
  DashboardGamesRoute: typeof DashboardGamesRouteWithChildren;
  DashboardMembersRoute: typeof DashboardMembersRoute;
  DashboardMembershipRoute: typeof DashboardMembershipRoute;
  DashboardProfileRoute: typeof DashboardProfileRouteWithChildren;
  DashboardReportsRoute: typeof DashboardReportsRoute;
  DashboardSettingsRoute: typeof DashboardSettingsRoute;
  DashboardTeamsRoute: typeof DashboardTeamsRouteWithChildren;
  DashboardIndexRoute: typeof DashboardIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCampaignsRoute: DashboardCampaignsRouteWithChildren,
  DashboardEventsRoute: DashboardEventsRouteWithChildren,
  DashboardGamesRoute: DashboardGamesRouteWithChildren,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardMembershipRoute: DashboardMembershipRoute,
  DashboardProfileRoute: DashboardProfileRouteWithChildren,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTeamsRoute: DashboardTeamsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

interface OnboardingRouteRouteChildren {
  OnboardingIndexRoute: typeof OnboardingIndexRoute;
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingIndexRoute: OnboardingIndexRoute,
};

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  EventsRoute: EventsRoute,
  SearchRoute: SearchRoute,
  EventEventIdRoute: EventEventIdRoute,
  GameGameIdRoute: GameGameIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiHealthServerRoute: ApiHealthServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiSocialBlockServerRoute: ApiSocialBlockServerRoute,
  ApiSocialBlocklistServerRoute: ApiSocialBlocklistServerRoute,
  ApiSocialFollowServerRoute: ApiSocialFollowServerRoute,
  ApiSocialRelationshipServerRoute: ApiSocialRelationshipServerRoute,
  ApiSocialUnblockServerRoute: ApiSocialUnblockServerRoute,
  ApiSocialUnfollowServerRoute: ApiSocialUnfollowServerRoute,
  ApiTestCleanupServerRoute: ApiTestCleanupServerRoute,
  ApiWebhooksSquareServerRoute: ApiWebhooksSquareServerRoute,
  ApiAuthActionProviderServerRoute: ApiAuthActionProviderServerRoute,
  ApiPaymentsSquareCallbackServerRoute: ApiPaymentsSquareCallbackServerRoute,
};
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>();
